In [1]:
! pip install googletrans==4.0.0-rc1 bs4

Requirement already satisfied: googletrans==4.0.0-rc1 in /home/mhira/miniconda3/envs/ezswitch/lib/python3.11/site-packages (4.0.0rc1)
Requirement already satisfied: bs4 in /home/mhira/miniconda3/envs/ezswitch/lib/python3.11/site-packages (0.0.2)
Requirement already satisfied: httpx==0.13.3 in /home/mhira/miniconda3/envs/ezswitch/lib/python3.11/site-packages (from googletrans==4.0.0-rc1) (0.13.3)
Requirement already satisfied: certifi in /home/mhira/miniconda3/envs/ezswitch/lib/python3.11/site-packages (from httpx==0.13.3->googletrans==4.0.0-rc1) (2025.11.12)
Requirement already satisfied: hstspreload in /home/mhira/miniconda3/envs/ezswitch/lib/python3.11/site-packages (from httpx==0.13.3->googletrans==4.0.0-rc1) (2025.1.1)
Requirement already satisfied: sniffio in /home/mhira/miniconda3/envs/ezswitch/lib/python3.11/site-packages (from httpx==0.13.3->googletrans==4.0.0-rc1) (1.3.1)
Requirement already satisfied: chardet==3.* in /home/mhira/miniconda3/envs/ezswitch/lib/python3.11/site-packages (from httpx==0.13.3->googletrans==4.0.0-rc1) (3.0.4)
Requirement already satisfied: idna==2.* in /home/mhira/miniconda3/envs/ezswitch/lib/python3.11/site-packages (from httpx==0.13.3->googletrans==4.0.0-rc1) (2.10)
Requirement already satisfied: rfc3986<2,>=1.3 in /home/mhira/miniconda3/envs/ezswitch/lib/python3.11/site-packages (from httpx==0.13.3->googletrans==4.0.0-rc1) (1.5.0)
Requirement already satisfied: httpcore==0.9.* in /home/mhira/miniconda3/envs/ezswitch/lib/python3.11/site-packages (from httpx==0.13.3->googletrans==4.0.0-rc1) (0.9.1)
Requirement already satisfied: h11<0.10,>=0.8 in /home/mhira/miniconda3/envs/ezswitch/lib/python3.11/site-packages (from httpcore==0.9.*->httpx==0.13.3->googletrans==4.0.0-rc1) (0.9.0)
Requirement already satisfied: h2==3.* in /home/mhira/miniconda3/envs/ezswitch/lib/python3.11/site-packages (from httpcore==0.9.*->httpx==0.13.3->googletrans==4.0.0-rc1) (3.2.0)
Requirement already satisfied: hyperframe<6,>=5.2.0 in /home/mhira/miniconda3/envs/ezswitch/lib/python3.11/site-packages (from h2==3.*->httpcore==0.9.*->httpx==0.13.3->googletrans==4.0.0-rc1) (5.2.0)
Requirement already satisfied: hpack<4,>=3.0 in /home/mhira/miniconda3/envs/ezswitch/lib/python3.11/site-packages (from h2==3.*->httpcore==0.9.*->httpx==0.13.3->googletrans==4.0.0-rc1) (3.0.0)
Requirement already satisfied: beautifulsoup4 in /home/mhira/miniconda3/envs/ezswitch/lib/python3.11/site-packages (from bs4) (4.14.3)
Requirement already satisfied: soupsieve>=1.6.1 in /home/mhira/miniconda3/envs/ezswitch/lib/python3.11/site-packages (from beautifulsoup4->bs4) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /home/mhira/miniconda3/envs/ezswitch/lib/python3.11/site-packages (from beautifulsoup4->bs4) (4.15.0)

In [3]:
import pandas as pd
import os

df = pd.read_parquet("hf://datasets/gentaiscool/codemixqa/data/test-00000-of-00001.parquet")

In [4]:
df

,id,original_index,problem,answer,topic,answer_type,multi_step,requires_reasoning,urls,method,language
0,2174-grammarforce_source-Bengali,2174,Which baseball field-এ Central Illinois Colleg...,Lloyd Hopkins Field,Sports,Place,False,False,https://www.altonbaseball.com/custom_pages/982...,grammarforce_source,Bengali
1,2429-grammarforce_target-Urdu,2429,Tivoli Gardens میں Demon کے لیے جگہ بنانے کو ک...,The Snake,Other,Other,False,False,https://sophiessuitcase.com/a-guide-to-tivoli-...,grammarforce_target,Urdu
2,3532-grammarforce_source-Hindi,3532,1898 में New York के state entomologist की 14t...,Byturus tomentosus,Science and technology,Other,True,False,https://nysl.ptfs.com/aw-server/rest/product/p...,grammarforce_source,Hindi
3,1452-selective-Italian,1452,After chi was Bullard Mountain named in the Bo...,Benjamin Bullard,Geography,Person,False,False,https://en.wikipedia.org/wiki/Bullard_Mountain...,selective,Italian
4,4184-force-Japanese,4184,What four 健康組織 wrote to President ジョン・F・ケネディ c...,"American Cancer Society, the American Public H...",History,Other,False,False,https://www.ajmc.com/view/surgeon-generals-smo...,random,Japanese
...,...,...,...,...,...,...,...,...,...,...,...
63995,4283-selective-Urdu transliterate,4283,kis month aur year mein Naughty Dog ke technol...,November 2023,Video games,Date,False,False,"https://en.wikipedia.org/wiki/Naughty_Dog,http...",selective,Urdu transliterate
63996,4287-selective-Urdu transliterate,4287,Which English singer aik film aur television c...,George Melly,Music,Person,False,False,https://tv.apple.com/us/person/george-melly/um...,selective,Urdu transliterate
63997,4291-selective-Urdu transliterate,4291,"MI5 ki pehli female DG kaun thi, aur pehla DG ...",Stella Rimington,Politics,Person,False,False,https://www.horus-security.co.uk/articles/nota...,selective,Urdu transliterate
63998,4306-selective-Urdu transliterate,4306,William Holwell Carr ke walid kya karte the zi...,Apothecary,Art,Other,False,False,https://en.wikipedia.org/wiki/William_Holwell_...,selective,Urdu transliterate
63999,4319-selective-Urdu transliterate,4319,Michigan ke Aloha Township ka naam muntakhib k...,James B. Patterson,Geography,Person,False,False,"https://en.wikipedia.org/wiki/Aloha_Township,h...",selective,Urdu transliterate

Created a folder with a dump of all the unique urls for each language

In [4]:
import pandas as pd

# Build a unique URL list and map each URL to a numeric id
all_urls = (
    df["urls"]
    .dropna()
    .str.split(",")
    .explode()
    .str.strip()
)
all_urls = all_urls[all_urls != ""]
unique_urls = pd.Series(all_urls.unique()).sort_values().reset_index(drop=True)

url_id_map = {url: idx for idx, url in enumerate(unique_urls, start=1)}

# Add columns:
# - url_list: list of URLs per row
# - url_ids: list of numeric ids corresponding to each URL
df["url_list"] = (
    df["urls"]
    .fillna("")
    .apply(lambda x: [u.strip() for u in x.split(",") if u.strip()])
)

def map_urls_to_ids(urls):
    return [url_id_map[u] for u in urls if u in url_id_map]

df["url_ids"] = df["url_list"].apply(map_urls_to_ids)

print(f"Total unique URLs: {len(unique_urls):,}")
print(df[["urls", "url_ids"]].head())

Total unique URLs: 2,939
                                                urls                url_ids
0  https://www.altonbaseball.com/custom_pages/982...            [1981, 908]
1  https://sophiessuitcase.com/a-guide-to-tivoli-...      [1768, 170, 1225]
2  https://nysl.ptfs.com/aw-server/rest/product/p...           [1608, 2339]
3  https://en.wikipedia.org/wiki/Bullard_Mountain...         [516, 334, 82]
4  https://www.ajmc.com/view/surgeon-generals-smo...  [1967, 232, 2565, 74]

In [5]:
# from collections import defaultdict

# dict_lang_ids = defaultdict(set)

# for _, row in df.iterrows():
#     lang = row["language"]
#     ids = row["url_ids"]
#     for id in ids:
#         dict_lang_ids[lang].add(id)

# # convert sets to sorted lists
# dict_lang_ids = {
#     lang: sorted(list(ids))
#     for lang, ids in dict_lang_ids.items()
# }

# print(dict_lang_ids)

# for key, val in dict_lang_ids.items():
#     print(key)
#     print(len(val))

In [6]:
df

,id,original_index,problem,answer,topic,answer_type,multi_step,requires_reasoning,urls,method,language,url_list,url_ids
0,2174-grammarforce_source-Bengali,2174,Which baseball field-এ Central Illinois Colleg...,Lloyd Hopkins Field,Sports,Place,False,False,https://www.altonbaseball.com/custom_pages/982...,grammarforce_source,Bengali,[https://www.altonbaseball.com/custom_pages/98...,"[1981, 908]"
1,2429-grammarforce_target-Urdu,2429,Tivoli Gardens میں Demon کے لیے جگہ بنانے کو ک...,The Snake,Other,Other,False,False,https://sophiessuitcase.com/a-guide-to-tivoli-...,grammarforce_target,Urdu,[https://sophiessuitcase.com/a-guide-to-tivoli...,"[1768, 170, 1225]"
2,3532-grammarforce_source-Hindi,3532,1898 में New York के state entomologist की 14t...,Byturus tomentosus,Science and technology,Other,True,False,https://nysl.ptfs.com/aw-server/rest/product/p...,grammarforce_source,Hindi,[https://nysl.ptfs.com/aw-server/rest/product/...,"[1608, 2339]"
3,1452-selective-Italian,1452,After chi was Bullard Mountain named in the Bo...,Benjamin Bullard,Geography,Person,False,False,https://en.wikipedia.org/wiki/Bullard_Mountain...,selective,Italian,[https://en.wikipedia.org/wiki/Bullard_Mountai...,"[516, 334, 82]"
4,4184-force-Japanese,4184,What four 健康組織 wrote to President ジョン・F・ケネディ c...,"American Cancer Society, the American Public H...",History,Other,False,False,https://www.ajmc.com/view/surgeon-generals-smo...,random,Japanese,[https://www.ajmc.com/view/surgeon-generals-sm...,"[1967, 232, 2565, 74]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
63995,4283-selective-Urdu transliterate,4283,kis month aur year mein Naughty Dog ke technol...,November 2023,Video games,Date,False,False,"https://en.wikipedia.org/wiki/Naughty_Dog,http...",selective,Urdu transliterate,"[https://en.wikipedia.org/wiki/Naughty_Dog, ht...","[1002, 60, 2930, 2296]"
63996,4287-selective-Urdu transliterate,4287,Which English singer aik film aur television c...,George Melly,Music,Person,False,False,https://tv.apple.com/us/person/george-melly/um...,selective,Urdu transliterate,[https://tv.apple.com/us/person/george-melly/u...,"[1847, 689, 1569]"
63997,4291-selective-Urdu transliterate,4291,"MI5 ki pehli female DG kaun thi, aur pehla DG ...",Stella Rimington,Politics,Person,False,False,https://www.horus-security.co.uk/articles/nota...,selective,Urdu transliterate,[https://www.horus-security.co.uk/articles/not...,"[2387, 1185, 1801]"
63998,4306-selective-Urdu transliterate,4306,William Holwell Carr ke walid kya karte the zi...,Apothecary,Art,Other,False,False,https://en.wikipedia.org/wiki/William_Holwell_...,selective,Urdu transliterate,[https://en.wikipedia.org/wiki/William_Holwell...,"[1276, 2566]"
63999,4319-selective-Urdu transliterate,4319,Michigan ke Aloha Township ka naam muntakhib k...,James B. Patterson,Geography,Person,False,False,"https://en.wikipedia.org/wiki/Aloha_Township,h...",selective,Urdu transliterate,"[https://en.wikipedia.org/wiki/Aloha_Township,...","[437, 1980, 61]"

In [45]:
# now store the unique urls in a file 
unique_urls.to_csv("unique_urls.csv", index=False)

In [46]:
# storing the mapping as well
url_id_df = pd.DataFrame({
    "url": list(url_id_map.keys()),
    "url_id": list(url_id_map.values())
})
url_id_df.to_csv("url_id_map.csv", index=False)

In [47]:
import requests
from bs4 import BeautifulSoup

# for each unique url, parse it and store it in a {id}.txt file

output_dir_lang = "language_texts"
os.makedirs(output_dir_lang, exist_ok=True)
def fetch_url_text(url, timeout=10):
    try:
        resp = requests.get(url, timeout=timeout, headers={
            "User-Agent": "Mozilla/5.0"
        })
        resp.raise_for_status()

        soup = BeautifulSoup(resp.text, "html.parser")

        # Remove scripts/styles
        for tag in soup(["script", "style", "noscript"]):
            tag.decompose()

        text = soup.get_text(separator=" ")
        text = " ".join(text.split())  # normalize whitespace
        return text

    except Exception as e:
        print(f"Failed to fetch {url}: {e}")
        return None

# tqdm for progress bar
from tqdm import tqdm
for url, url_id in tqdm(url_id_map.items()):
    text = fetch_url_text(url)
    if text:
        with open(os.path.join(output_dir_lang, f"{url_id}.txt"), "w", encoding="utf-8") as f:
            f.write(text)

  0%|          | 0/2939 [00:00<?, ?it/s]

Failed to fetch 'https://en.wikipedia.org/wiki/Ben_M._Bogard': No connection adapters were found for "'https://en.wikipedia.org/wiki/Ben_M._Bogard'"
Failed to fetch 'https://en.wikipedia.org/wiki/Lygia_Pape': No connection adapters were found for "'https://en.wikipedia.org/wiki/Lygia_Pape'"
Failed to fetch 'https://en.wikipedia.org/wiki/Omsund_Bridge': No connection adapters were found for "'https://en.wikipedia.org/wiki/Omsund_Bridge'"
Failed to fetch 'https://en.wikipedia.org/wiki/S%C3%BCleymaniye_Mosque': No connection adapters were found for "'https://en.wikipedia.org/wiki/S%C3%BCleymaniye_Mosque'"
Failed to fetch Hillhttps://en.wikipedia.org/wiki/Margaret_Gardiner_(art_collector): No connection adapters were found for 'Hillhttps://en.wikipedia.org/wiki/Margaret_Gardiner_(art_collector)'
Failed to fetch chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/https://www.ams.org/notices/199808/comm-fulkerson.pdf: No connection adapters were found for 'chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/https://www.ams.org/notices/199808/comm-fulkerson.pdf'

  0%|          | 7/2939 [00:00<01:49, 26.90it/s]

Failed to fetch http://astro.vaporia.com/start/granat.html: 406 Client Error: Not Acceptable for url: http://astro.vaporia.com/start/granat.html

  0%|          | 12/2939 [00:01<09:10,  5.31it/s]

Failed to fetch http://deborahzcass.org/index-764.html: 404 Client Error: Not Found for url: http://deborahzcass.org/index-764.html

  0%|          | 13/2939 [00:02<11:21,  4.30it/s]

Failed to fetch http://eyeway.org.in/?q=ronnie-lee-milsap: HTTPSConnectionPool(host='eyeway.org.in', port=443): Max retries exceeded with url: /?q=ronnie-lee-milsap (Caused by SSLError(CertificateError("hostname 'eyeway.org.in' doesn't match 'www.eyeway.org.in'")))

  1%|          | 21/2939 [00:08<27:28,  1.77it/s]

Failed to fetch http://m.koausa.org/dnwalli/index.html: HTTPConnectionPool(host='m.koausa.org', port=80): Max retries exceeded with url: /dnwalli/index.html (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f02878b2590>: Failed to establish a new connection: [Errno -2] Name or service not known'))
Failed to fetch http://npshistory.com/newsletters/inside-earth/v9n1.pdf: 403 Client Error: Forbidden for url: http://npshistory.com/newsletters/inside-earth/v9n1.pdf
Failed to fetch http://parkscanadahistory.com/publications/richelieu-river-heritage-guide-eng.pdf: 403 Client Error: Forbidden for url: http://parkscanadahistory.com/publications/richelieu-river-heritage-guide-eng.pdf

  1%|          | 23/2939 [00:18<1:43:35,  2.13s/it]

Failed to fetch http://powerplants.warbirdsresourcegroup.org/unitedstates_powerplants_P-W_R-1340_Wasp.html: HTTPSConnectionPool(host='powerplants.warbirdsresourcegroup.org', port=443): Read timed out. (read timeout=10)

  1%|▏         | 41/2939 [00:24<15:06,  3.20it/s]

Failed to fetch http://www.enjoyed.today/Henry_Draper_Catalogue/: 404 Client Error: Not Found for url: http://www.enjoyed.today/Henry_Draper_Catalogue/

  1%|▏         | 42/2939 [00:25<13:53,  3.47it/s]

Failed to fetch http://www.enjoyed.today/Vonnegut_(crater)/: 404 Client Error: Not Found for url: http://www.enjoyed.today/Vonnegut_(crater)/

  2%|▏         | 45/2939 [00:28<40:12,  1.20it/s]

Failed to fetch http://www.ignou.ac.in/upload/convocationall.htm: 404 Client Error:  for url: https://www.ignou.ac.in/upload/convocationall.htm

  2%|▏         | 53/2939 [01:10<6:42:18,  8.36s/it]

Failed to fetch http://www.redsoxdiehard.com/worldseries/players/wakefield.html: 502 Server Error: Bad Gateway or Proxy Error for url: http://www.redsoxdiehard.com/worldseries/players/wakefield.html

  2%|▏         | 55/2939 [01:11<3:30:08,  4.37s/it]

Failed to fetch https://032c.com/magazine/smash-what-is-left-to-be-smashed-jun-takahashis-undercover: 404 Client Error: Not Found for url: https://www.032c.com/magazine/smash-what-is-left-to-be-smashed-jun-takahashis-undercover

  2%|▏         | 63/2939 [01:16<34:07,  1.40it/s]

Failed to fetch https://aabworld.com/sony-alpha-1-mirrorless-digital-camera-body-only: 403 Client Error: Forbidden for url: https://aabworld.com/sony-alpha-1-mirrorless-digital-camera-body-only

  3%|▎         | 75/2939 [01:27<32:59,  1.45it/s]

Failed to fetch https://acsjournals.onlinelibrary.wiley.com/doi/10.3322/caac.21210: 403 Client Error: Forbidden for url: https://acsjournals.onlinelibrary.wiley.com/doi/10.3322/caac.21210
Failed to fetch https://addisonmi.us/about-us: HTTPSConnectionPool(host='addisonmi.us', port=443): Max retries exceeded with url: /about-us (Caused by SSLError(CertificateError("hostname 'addisonmi.us' doesn't match either of 'lylemn.org', 'www.lylemn.org'")))

  3%|▎         | 76/2939 [01:28<39:15,  1.22it/s]

Failed to fetch https://afj.org/nominee/natasha-merle/: 403 Client Error: Forbidden for url: https://afj.org/nominee/natasha-merle/

  3%|▎         | 78/2939 [01:29<26:14,  1.82it/s]

Failed to fetch https://african-research.com/research/political-history/remembering-the-late-kow-nkensen-arkaah/: 406 Client Error: Not Acceptable for url: https://african-research.com/research/political-history/remembering-the-late-kow-nkensen-arkaah/

  3%|▎         | 82/2939 [01:29<13:56,  3.42it/s]

Failed to fetch https://ago.ca/agoinsider/retroago-go-back-1922-and-explore-agos-first-one-woman-show: 403 Client Error: Forbidden for url: https://ago.ca/agoinsider/retroago-go-back-1922-and-explore-agos-first-one-woman-show
Failed to fetch https://aishwaryasandeep.in/biography-of-chief-justice-lalit-mohan-sharma/: HTTPSConnectionPool(host='aishwaryasandeep.in', port=443): Max retries exceeded with url: /biography-of-chief-justice-lalit-mohan-sharma/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f02895c5390>: Failed to establish a new connection: [Errno -2] Name or service not known'))

  3%|▎         | 100/2939 [01:31<08:33,  5.53it/s]

Failed to fetch https://aldeilis.net/terror/1333.pdf: 404 Client Error: Not Found for url: https://aldeilis.net/terror/1333.pdf

  3%|▎         | 101/2939 [01:32<08:22,  5.65it/s]

Failed to fetch https://aminoapps.com/c/lemonadebarbies/page/item/lemonade-album/dP7k_MMSaIm87gdxWYq34En4LEMbvY8bP3: HTTPSConnectionPool(host='aminoapps.com', port=443): Max retries exceeded with url: /c/lemonadebarbies/page/item/lemonade-album/dP7k_MMSaIm87gdxWYq34En4LEMbvY8bP3 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0289885c50>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))

  4%|▍         | 112/2939 [01:35<06:54,  6.82it/s]

Failed to fetch https://answersafrica.com/inside-lucas-radebes-life-with-wife-thobela-silver-after-losing-feziwe-faith.html: 403 Client Error: Forbidden for url: https://answersafrica.com/inside-lucas-radebes-life-with-wife-thobela-silver-after-losing-feziwe-faith.html
Failed to fetch https://answersafrica.com/who-is-matthew-mcclurkin-donnie-mcclurkins-son.html: 403 Client Error: Forbidden for url: https://answersafrica.com/who-is-matthew-mcclurkin-donnie-mcclurkins-son.html

  4%|▍         | 115/2939 [01:35<06:23,  7.36it/s]

Failed to fetch https://app.smartify.org/en-GB/artists/robert-adams-whdbn: 403 Client Error: Forbidden for url: https://app.smartify.org/en-GB/artists/robert-adams-whdbn

  4%|▍         | 126/2939 [01:53<1:11:26,  1.52s/it]

Failed to fetch https://archive.ph/20140726204034/http://examiner-enterprise.com/sections/opinion/columnists/lost-bartlesville-day-president-came-town-and-love-lifetime%E2%80%A6.html: 429 Client Error: Too Many Requests for url: https://archive.ph/20140726204034/http://examiner-enterprise.com/sections/opinion/columnists/lost-bartlesville-day-president-came-town-and-love-lifetime%E2%80%A6.html

  4%|▍         | 127/2939 [01:53<57:51,  1.23s/it]

Failed to fetch https://archive.ph/20201019191835/https://www.world.rugby/match/23378: 429 Client Error: Too Many Requests for url: https://archive.ph/20201019191835/https://www.world.rugby/match/23378

  5%|▍         | 141/2939 [01:58<19:18,  2.42it/s]

Failed to fetch https://artistnepal.com/artist/narayan-gopal/: 404 Client Error: Not Found for url: https://artistnepal.com/artist/narayan-gopal/
Failed to fetch https://arts.columbia.edu/news/who-we-are-miya-masaoka: 403 Client Error: Forbidden for url: https://arts.columbia.edu/news/who-we-are-miya-masaoka

  5%|▌         | 148/2939 [02:01<22:14,  2.09it/s]

Failed to fetch https://artuk.org/discover/artworks/christopher-codrington-16681710-275554: 403 Client Error: Forbidden for url: https://artuk.org/discover/artworks/christopher-codrington-16681710-275554

  5%|▌         | 149/2939 [02:02<19:41,  2.36it/s]

Failed to fetch https://artuk.org/visit/venues/national-trust-chartwell-7431: 403 Client Error: Forbidden for url: https://artuk.org/visit/venues/national-trust-chartwell-7431

  5%|▌         | 151/2939 [02:02<17:34,  2.64it/s]

Failed to fetch https://arvida.saguenay.ca/en/the-city-of-aluminum/history-br-and-profile-of-arvida/ligne-du-temps: 404 Client Error: Not Found for url: https://arvida.saguenay.ca/en/the-city-of-aluminum/history-br-and-profile-of-arvida/ligne-du-temps

  5%|▌         | 158/2939 [02:19<39:08,  1.18it/s]

Failed to fetch https://awards.acm.org/award-recipients/balakrishnan_4440475: 403 Client Error: Forbidden for url: https://awards.acm.org/award-recipients/balakrishnan_4440475
Failed to fetch https://awards.acm.org/award_winners/kleinberg_0032532: 403 Client Error: Forbidden for url: https://awards.acm.org/award_winners/kleinberg_0032532

  5%|▌         | 161/2939 [02:19<19:18,  2.40it/s]

Failed to fetch https://awardswatch.com/drake-taylor-swift-post-malone-cardi-b-rule-billboard-year-end-hot-100-songs-and-albums/: 406 Client Error: Not Acceptable for url: https://awardswatch.com/drake-taylor-swift-post-malone-cardi-b-rule-billboard-year-end-hot-100-songs-and-albums/

  6%|▌         | 168/2939 [02:30<1:10:40,  1.53s/it]

Failed to fetch https://benjamins.com/catalog/ap.20014.har: 403 Client Error: Forbidden for url: https://benjamins.com/catalog/ap.20014.har

  6%|▌         | 172/2939 [02:33<43:57,  1.05it/s]

Failed to fetch https://betsapi.com/t/16016/Eintracht-Frankfurt: 403 Client Error: Forbidden for url: https://betsapi.com/t/16016/Eintracht-Frankfurt

  6%|▌         | 178/2939 [02:38<42:54,  1.07it/s]

Failed to fetch https://biodiversity.org.au/nsl/services/rest/instance/apni/496609: 403 Client Error: Forbidden for url: https://biodiversity.org.au/nsl/services/rest/instance/apni/496609

  6%|▌         | 183/2939 [02:41<30:27,  1.51it/s]

Failed to fetch https://blog.goo.ne.jp/tk-80/e/10c1fa49f06be35a562ca19bedaa647b: 403 Client Error: Forbidden for url: https://blog.goo.ne.jp/tk-80/e/10c1fa49f06be35a562ca19bedaa647b

  7%|▋         | 203/2939 [02:47<11:57,  3.81it/s]

Failed to fetch https://boxrec.com/wiki/index.php/Jackson_Asiku: 403 Client Error: Forbidden for url: https://boxrec.com/wiki/index.php/Jackson_Asiku

  7%|▋         | 205/2939 [02:48<14:49,  3.07it/s]

Failed to fetch https://brandsouthafrica.com/111255/sports-news/world-cup-stadiums/: 403 Client Error: Forbidden for url: https://brandsouthafrica.com/111255/sports-news/world-cup-stadiums/

  7%|▋         | 211/2939 [02:50<12:29,  3.64it/s]

Failed to fetch https://britishlistedbuildings.co.uk/101090695-bede-cottage-stonehouse: 403 Client Error: Forbidden for url: https://britishlistedbuildings.co.uk/101090695-bede-cottage-stonehouse
Failed to fetch https://britishlistedbuildings.co.uk/101180136-sculpture-depicting-ceres-in-belvoir-castle-sculpture-garden-one-of-seven-statues-belvoir: 403 Client Error: Forbidden for url: https://britishlistedbuildings.co.uk/101180136-sculpture-depicting-ceres-in-belvoir-castle-sculpture-garden-one-of-seven-statues-belvoir

  7%|▋         | 213/2939 [02:53<32:55,  1.38it/s]

Failed to fetch https://byjus.com/question-answer/match-the-following-doabs-in-punjab-with-the-rivers-that-surround-them-chenab-and-jhelumbeas/: 502 Server Error: Bad Gateway for url: https://byjus.com/question-answer/match-the-following-doabs-in-punjab-with-the-rivers-that-surround-them-chenab-and-jhelumbeas/

  7%|▋         | 215/2939 [02:54<26:02,  1.74it/s]

Failed to fetch https://byjus.com/question-answer/which-of-the-following-is-known-as-the-lion-s-mouth-brahmaputra-ganga-indus-yamuna/: 502 Server Error: Bad Gateway for url: https://byjus.com/question-answer/which-of-the-following-is-known-as-the-lion-s-mouth-brahmaputra-ganga-indus-yamuna/

  8%|▊         | 222/2939 [02:58<14:59,  3.02it/s]

Failed to fetch https://cashtvogue.s3.waw.io.cloud.ovh.net/is-adore-delano-trans-sexuality-partner-and.html: HTTPSConnectionPool(host='cashtvogue.s3.waw.io.cloud.ovh.net', port=443): Max retries exceeded with url: /is-adore-delano-trans-sexuality-partner-and.html (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f028b1eea10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

  8%|▊         | 226/2939 [03:02<39:51,  1.13it/s]

Failed to fetch https://cfseu.bc.ca/gangster-profile/: 404 Client Error: Not Found for url: https://cfseu.bc.ca/gangster-profile/

  8%|▊         | 228/2939 [03:03<28:46,  1.57it/s]

Failed to fetch https://christchurchartgallery.org.nz/collection/9565/doris-lusk/power-house-tuai: HTTPSConnectionPool(host='christchurchartgallery.org.nz', port=443): Max retries exceeded with url: /collection/9565/doris-lusk/power-house-tuai (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0288875a10>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))

  8%|▊         | 234/2939 [03:05<16:15,  2.77it/s]

Failed to fetch https://citeseerx.ist.psu.edu/document?repid=rep1&type=pdf&doi=f234b9ef394b5c71b7a438fe833b0ead3bca9d3f: HTTPSConnectionPool(host='citeseerx.ist.psu.edu', port=443): Max retries exceeded with url: /document?repid=rep1&type=pdf&doi=f234b9ef394b5c71b7a438fe833b0ead3bca9d3f (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1016)')))
Failed to fetch https://citizen-burger-disorder.fandom.com/wiki/Operation_Desert_Storm: 410 Client Error: Gone for url: https://citizen-burger-disorder.fandom.com/wiki/Operation_Desert_Storm

  8%|▊         | 246/2939 [03:12<15:30,  2.89it/s]

Failed to fetch https://commongroundscorecard.org/mike-lawler/: HTTPSConnectionPool(host='commongroundscorecard.org', port=443): Max retries exceeded with url: /mike-lawler/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f028bf4e010>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))

  9%|▊         | 250/2939 [03:12<08:54,  5.03it/s]

Failed to fetch https://commons.erau.edu/cgi/viewcontent.cgi?article=1567&context=jaaer: 403 Client Error: Forbidden for url: https://commons.erau.edu/cgi/viewcontent.cgi?article=1567&context=jaaer

  9%|▊         | 256/2939 [03:13<05:28,  8.17it/s]

Failed to fetch https://commons.wikimedia.org/wiki/File:Eugene_Bullard_interviewed_on_NBC%27s_Today_Show: 404 Client Error: Not Found for url: https://commons.wikimedia.org/wiki/File:Eugene_Bullard_interviewed_on_NBC%27s_Today_Show
Failed to fetch https://commons.wikimedia.org/wiki/File:Fastest_growing_languages_of_India_%E2%80%94_Hindi_(first): 404 Client Error: Not Found for url: https://commons.wikimedia.org/wiki/File:Fastest_growing_languages_of_India_%E2%80%94_Hindi_(first)

  9%|▉         | 261/2939 [03:14<10:08,  4.40it/s]

Failed to fetch https://content.time.com/time/specials/packages/article/0: 404 Client Error: Not Found for url: https://content.time.com/time/specials/packages/article/0

  9%|▉         | 264/2939 [03:24<1:09:11,  1.55s/it]

Failed to fetch https://core.ac.uk/download/pdf/188225915.pdf: HTTPSConnectionPool(host='files01.core.ac.uk', port=443): Read timed out. (read timeout=10)

  9%|▉         | 268/2939 [03:26<38:45,  1.15it/s]

Failed to fetch https://crediblemind.com/videos/the-surprisingly-dramatic-role-of-nutrition-in-mental-health-julia: 404 Client Error: Not Found for url: https://crediblemind.com/videos/the-surprisingly-dramatic-role-of-nutrition-in-mental-health-julia
Failed to fetch https://crsreports.congress.gov/product/pdf/IF/IF12194: 403 Client Error: Forbidden for url: https://crsreports.congress.gov/product/pdf/IF/IF12194

 10%|▉         | 281/2939 [03:38<19:58,  2.22it/s]

Failed to fetch https://datacommons.iitm.ac.in/place/wikidataId/Q5828162: 502 Server Error: Bad Gateway for url: https://datacommons.iitm.ac.in/place/wikidataId/Q5828162

 10%|█         | 297/2939 [03:45<40:27,  1.09it/s]

Failed to fetch https://decodingworldaffairs.com/justice-awaited-even-after-30-years-of-exodus-of-kashmiri-pundits/: HTTPSConnectionPool(host='decodingworldaffairs.com', port=443): Max retries exceeded with url: /justice-awaited-even-after-30-years-of-exodus-of-kashmiri-pundits/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0287ba6ad0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))

 10%|█         | 299/2939 [03:46<26:39,  1.65it/s]

Failed to fetch https://demokratizatsiya.pub/archives/07-2_arias.pdf: 404 Client Error: Not Found for url: https://www.demokratizatsiya.pub/archives/07-2_arias.pdf

 10%|█         | 306/2939 [03:53<35:16,  1.24it/s]

Failed to fetch https://digitalcommons.usf.edu/cgi/viewcontent.cgi?article=1007&context=inside_earth: 403 Client Error: Forbidden for url: https://digitalcommons.usf.edu/cgi/viewcontent.cgi?article=1007&context=inside_earth

 10%|█         | 308/2939 [03:53<20:07,  2.18it/s]

Failed to fetch https://dkprintworld.com/author-book/ratan-parimoo/: 403 Client Error: Forbidden for url: https://dkprintworld.com/author-book/ratan-parimoo/

 11%|█         | 322/2939 [04:06<58:56,  1.35s/it]

Failed to fetch https://dst.gov.in/national-super-computing-mission: 404 Client Error: Not Found for url: https://dst.gov.in/national-super-computing-mission
Failed to fetch https://dubai-times.com/luxury-lifestyle-dubai/cloud-seeding-in-uae-increases-rains-by-over-25-percent.html: 406 Client Error: Not Acceptable for url: https://dubai-times.com/luxury-lifestyle-dubai/cloud-seeding-in-uae-increases-rains-by-over-25-percent.html

 11%|█         | 323/2939 [04:06<45:29,  1.04s/it]

Failed to fetch https://dungeonsanddragonsfan.com/ardling-one-dnd-news/: 406 Client Error: Not Acceptable for url: https://dungeonsanddragonsfan.com/ardling-one-dnd-news/

 11%|█         | 329/2939 [04:49<5:16:05,  7.27s/it]

Failed to fetch https://eclipsewise.com/solar/SEprime/1801-1900/SE1805Jan01Pprime.html: 406 Client Error: Not Acceptable for url: https://eclipsewise.com/solar/SEprime/1801-1900/SE1805Jan01Pprime.html

 11%|█▏        | 336/2939 [04:52<46:14,  1.07s/it]

Failed to fetch https://electronics.sony.com/imaging/interchangeable-lens-cameras/all-interchangeable-lens-cameras/p/ilce1-b: 403 Client Error: Forbidden for url: https://electronics.sony.com/imaging/interchangeable-lens-cameras/all-interchangeable-lens-cameras/p/ilce1-b

 12%|█▏        | 345/2939 [05:11<1:17:34,  1.79s/it]

Failed to fetch https://en.dev.wikipedia-on-ipfs.org/wiki/Konaruiyeh: HTTPSConnectionPool(host='en.dev.wikipedia-on-ipfs.org', port=443): Max retries exceeded with url: /wiki/Konaruiyeh (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f02893830d0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))

 12%|█▏        | 347/2939 [05:11<44:53,  1.04s/it]

Failed to fetch https://en.geneastar.org/genealogy/tioliern/nicolas-pierre-tiolier: 403 Client Error: Forbidden for url: https://en.geneastar.org/genealogy/tioliern/nicolas-pierre-tiolier

 12%|█▏        | 351/2939 [05:13<21:55,  1.97it/s]

Failed to fetch https://en.m.wikipedia.org/wiki/File:Mucha: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/File:Mucha

 12%|█▏        | 353/2939 [05:13<13:41,  3.15it/s]

Failed to fetch https://en.numista.com/catalogue/artist.php?id=509: 403 Client Error: Forbidden for url: https://en.numista.com/catalogue/artist.php?id=509
Failed to fetch https://en.numista.com/catalogue/note201000.html: 403 Client Error: Forbidden for url: https://en.numista.com/catalogue/note201000.html

 12%|█▏        | 356/2939 [05:15<19:20,  2.23it/s]

Failed to fetch https://en.wal.unesco.org/languages/aralle-tabulahan: 503 Server Error: Service Unavailable for url: https://en.wal.unesco.org/languages/aralle-tabulahan

 19%|█▊        | 545/2939 [05:38<04:19,  9.23it/s]

Failed to fetch https://en.wikipedia.org/wiki/Cheyyar_Division_(Highways): 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Cheyyar_Division_(Highways)

 21%|██        | 615/2939 [05:48<04:37,  8.38it/s]

Failed to fetch https://en.wikipedia.org/wiki/Dogra_Art_Museum: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Dogra_Art_Museum

 21%|██        | 621/2939 [05:49<04:41,  8.23it/s]

Failed to fetch https://en.wikipedia.org/wiki/Douglas_Bennett_(cricketer: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Douglas_Bennett_(cricketer

 22%|██▏       | 656/2939 [05:53<05:21,  7.11it/s]

Failed to fetch https://en.wikipedia.org/wiki/Federal_Insecticide: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Federal_Insecticide

 23%|██▎       | 682/2939 [05:56<04:45,  7.90it/s]

Failed to fetch https://en.wikipedia.org/wiki/Gay_Men%27s_Chorus_of_Washington: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Gay_Men%27s_Chorus_of_Washington

 23%|██▎       | 684/2939 [05:56<05:40,  6.62it/s]

Failed to fetch https://en.wikipedia.org/wiki/Gay_Men's_Chorus_of_Washington: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Gay_Men's_Chorus_of_Washington

 27%|██▋       | 781/2939 [06:09<08:37,  4.17it/s]

Failed to fetch https://en.wikipedia.org/wiki/Islamia_College_of_Science_and_Commerce: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Islamia_College_of_Science_and_Commerce

 29%|██▉       | 851/2939 [06:18<05:56,  5.85it/s]

Failed to fetch https://en.wikipedia.org/wiki/Kim_Tae-young_(footballer: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Kim_Tae-young_(footballer

 29%|██▉       | 854/2939 [06:18<05:41,  6.11it/s]

Failed to fetch https://en.wikipedia.org/wiki/King_Schools: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/King_Schools

 32%|███▏      | 951/2939 [06:33<02:51, 11.61it/s]

Failed to fetch https://en.wikipedia.org/wiki/Mary_Letitia_Caldwella: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Mary_Letitia_Caldwella

 35%|███▍      | 1020/2939 [06:41<02:30, 12.71it/s]

Failed to fetch https://en.wikipedia.org/wiki/Odd_Fellows_Hall_(Eureka: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Odd_Fellows_Hall_(Eureka

 35%|███▌      | 1042/2939 [06:44<04:45,  6.63it/s]

Failed to fetch https://en.wikipedia.org/wiki/Pakistan_Business_Council: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Pakistan_Business_Council

 38%|███▊      | 1116/2939 [06:54<03:52,  7.84it/s]

Failed to fetch https://en.wikipedia.org/wiki/Risen_Christ_%28Michelangelo: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Risen_Christ_%28Michelangelo
Failed to fetch https://en.wikipedia.org/wiki/Risen_Christ_(Michelangelo: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Risen_Christ_(Michelangelo

 40%|███▉      | 1172/2939 [07:01<04:01,  7.31it/s]

Failed to fetch https://en.wikipedia.org/wiki/Solar_eclipse_of_June_21: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Solar_eclipse_of_June_21

 40%|████      | 1177/2939 [07:01<04:16,  6.87it/s]

Failed to fetch https://en.wikipedia.org/wiki/Spring_Rock_Township: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Spring_Rock_Township

 42%|████▏     | 1231/2939 [07:07<03:56,  7.22it/s]

Failed to fetch https://en.wikipedia.org/wiki/Tramcar_(Wildwood: 404 Client Error: Not Found for url: https://en.wikipedia.org/wiki/Tramcar_(Wildwood

 44%|████▍     | 1301/2939 [07:15<03:06,  8.77it/s]

Failed to fetch https://en.wikisource.org/wiki/1911_Encyclop%C3%A6dia_Britannica/Watteau: 404 Client Error: Not Found for url: https://en.wikisource.org/wiki/1911_Encyclop%C3%A6dia_Britannica/Watteau

 44%|████▍     | 1303/2939 [07:15<04:02,  6.75it/s]

Failed to fetch https://encyclopedia.pub/entry/28577: 403 Client Error: Forbidden for url: https://encyclopedia.pub/entry/28577
Failed to fetch https://encyclopedia.pub/entry/35183: 403 Client Error: Forbidden for url: https://encyclopedia.pub/entry/35183

 44%|████▍     | 1307/2939 [07:16<04:11,  6.50it/s]

Failed to fetch https://engineering.ucdavis.edu/people/raissa-dsouza: 403 Client Error: Forbidden for url: https://engineering.ucdavis.edu/people/raissa-dsouza

 45%|████▍     | 1308/2939 [07:22<37:20,  1.37s/it]

Failed to fetch https://eol.org/ar/pages/919944/articles: HTTPSConnectionPool(host='eol.org', port=443): Max retries exceeded with url: /ar/pages/919944/articles (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1016)')))

 45%|████▍     | 1310/2939 [07:22<24:53,  1.09it/s]

Failed to fetch https://eprints.soas.ac.uk/36141/1/The%20facilitative%20use%20of%20learner-initiated%20translanguaging.pdf: 403 Client Error: Forbidden for url: https://soas-repository.worktribe.com/output/332588

 45%|████▌     | 1326/2939 [07:30<05:37,  4.78it/s]

Failed to fetch https://fbref.com/en/squads/822bd0ba/2021-2022/c514/Liverpool-Stats-FA-Cup: 403 Client Error: Forbidden for url: https://fbref.com/en/squads/822bd0ba/2021-2022/c514/Liverpool-Stats-FA-Cup

 45%|████▌     | 1331/2939 [07:32<05:37,  4.77it/s]

Failed to fetch https://fineart.ha.com/heritage-auctions-press-releases-and-news/j.c.-leyendecker-saturday-evening-post-cover-sells-for-4.1-million-at-heritage-auctions-to-shatter-world-record.s?releaseId=4178: 403 Client Error: Forbidden for url: https://fineart.ha.com/heritage-auctions-press-releases-and-news/j.c.-leyendecker-saturday-evening-post-cover-sells-for-4.1-million-at-heritage-auctions-to-shatter-world-record.s?releaseId=4178

 45%|████▌     | 1333/2939 [07:32<07:51,  3.40it/s]

Failed to fetch https://follies-trust.org/product/tollymore-park/: 406 Client Error: Not Acceptable for url: https://follies-trust.org/product/tollymore-park/

 45%|████▌     | 1334/2939 [07:33<07:36,  3.52it/s]

Failed to fetch https://follies-trust.org/projects/projects-2010-11/lord-limericks-follies/: 406 Client Error: Not Acceptable for url: https://follies-trust.org/projects/projects-2010-11/lord-limericks-follies/

 46%|████▌     | 1338/2939 [07:34<07:35,  3.51it/s]

Failed to fetch https://forums.atariage.com/topic/342130-triym-ym2203-fm-ym2149-comp-soundcard/: 403 Client Error: Forbidden for url: https://forums.atariage.com/topic/342130-triym-ym2203-fm-ym2149-comp-soundcard/

 46%|████▌     | 1340/2939 [07:35<09:27,  2.82it/s]

Failed to fetch https://frenchbanknotes.com/artists.php?artist=Pfund%2C+R.: 406 Client Error: Not Acceptable for url: https://frenchbanknotes.com/artists.php?artist=Pfund%2C+R.

 46%|████▌     | 1343/2939 [07:37<12:27,  2.13it/s]

Failed to fetch https://fsi.nic.in/isfr19/vol2/isfr-2019-vol-ii-goa.pdf: HTTPSConnectionPool(host='fsi.nic.in', port=443): Max retries exceeded with url: /isfr19/vol2/isfr-2019-vol-ii-goa.pdf (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1016)')))

 46%|████▌     | 1344/2939 [07:37<12:52,  2.07it/s]

Failed to fetch https://fsi.nic.in/isfr19/vol2/isfr-2019-vol-ii-sikkim.pdf: HTTPSConnectionPool(host='fsi.nic.in', port=443): Max retries exceeded with url: /isfr19/vol2/isfr-2019-vol-ii-sikkim.pdf (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1016)')))

 46%|████▌     | 1345/2939 [07:38<13:10,  2.02it/s]

Failed to fetch https://fsi.nic.in/isfr2019/isfr-fsi-vol2.pdf: HTTPSConnectionPool(host='fsi.nic.in', port=443): Max retries exceeded with url: /isfr2019/isfr-fsi-vol2.pdf (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1016)')))

 46%|████▌     | 1349/2939 [07:51<56:04,  2.12s/it]

Failed to fetch https://garrowayatlarge.com/index.php/category/daves-life/page/3/: 406 Client Error: Not Acceptable for url: https://garrowayatlarge.com/index.php/category/daves-life/page/3/

 46%|████▌     | 1354/2939 [07:52<15:38,  1.69it/s]

Failed to fetch https://genius.com/Green-day-welcome-to-paradise-kerplunk-version-lyrics/q/release-date: 403 Client Error: Forbidden for url: https://genius.com/Green-day-welcome-to-paradise-kerplunk-version-lyrics/q/release-date
Failed to fetch https://genius.com/Mariah-carey-hero-lyrics: 403 Client Error: Forbidden for url: https://genius.com/Mariah-carey-hero-lyrics
Failed to fetch https://genius.com/Nomeansno-the-river-lyrics: 403 Client Error: Forbidden for url: https://genius.com/Nomeansno-the-river-lyrics
Failed to fetch https://genius.com/Relient-k-may-the-horse-be-with-you-lyrics: 403 Client Error: Forbidden for url: https://genius.com/Relient-k-may-the-horse-be-with-you-lyrics

 46%|████▌     | 1358/2939 [07:52<07:34,  3.48it/s]

Failed to fetch https://genius.com/The-living-tombstone-alastors-game-lyrics: 403 Client Error: Forbidden for url: https://genius.com/The-living-tombstone-alastors-game-lyrics
Failed to fetch https://genius.com/Tlc-lets-do-it-again-lyrics/q/writer: 403 Client Error: Forbidden for url: https://genius.com/Tlc-lets-do-it-again-lyrics/q/writer
Failed to fetch https://genius.com/albums/Adore-delano/Dirty-laundry-ep: 403 Client Error: Forbidden for url: https://genius.com/albums/Adore-delano/Dirty-laundry-ep
Failed to fetch https://genius.com/albums/Alec-benjamin/These-two-windows: 403 Client Error: Forbidden for url: https://genius.com/albums/Alec-benjamin/These-two-windows

 46%|████▋     | 1360/2939 [07:52<05:35,  4.71it/s]

Failed to fetch https://genius.com/albums/Machine-girl/Phantom-tracks: 403 Client Error: Forbidden for url: https://genius.com/albums/Machine-girl/Phantom-tracks
Failed to fetch https://getsol.app/profile/Gloria-Niemeyer-Francke-1922: 404 Client Error: Not Found for url: https://getsol.app/profile/Gloria-Niemeyer-Francke-1922
Failed to fetch https://getsol.app/profile/William-Prager-1903: 404 Client Error: Not Found for url: https://getsol.app/profile/William-Prager-1903

 46%|████▋     | 1362/2939 [07:52<04:23,  5.98it/s]

Failed to fetch https://getsongkey.com/song/i-offer-my-life/YWv9K: 403 Client Error: Forbidden for url: https://getsongkey.com/song/i-offer-my-life/YWv9K

 47%|████▋     | 1370/2939 [07:56<07:07,  3.67it/s]

Failed to fetch https://globalnation.inquirer.net/129594/the-olympic-triumph-of-vicki-manalo-draves: 403 Client Error: Forbidden for url: https://globalnation.inquirer.net/129594/the-olympic-triumph-of-vicki-manalo-draves

 47%|████▋     | 1372/2939 [07:57<09:23,  2.78it/s]

Failed to fetch https://go.drugbank.com/drugs/DB11150: 403 Client Error: Forbidden for url: https://go.drugbank.com/drugs/DB11150
Failed to fetch https://go.drugbank.com/drugs/DB16098: 403 Client Error: Forbidden for url: https://go.drugbank.com/drugs/DB16098

 47%|████▋     | 1377/2939 [07:58<05:50,  4.45it/s]

Failed to fetch https://graphsearch.epfl.ch/en/concept/1524880: 403 Client Error: Forbidden for url: https://graphsearch.epfl.ch/en/concept/1524880
Failed to fetch https://graphsearch.epfl.ch/fr/concept/10705509: 403 Client Error: Forbidden for url: https://graphsearch.epfl.ch/fr/concept/10705509
Failed to fetch https://graphsearch.epfl.ch/fr/concept/52198543: 403 Client Error: Forbidden for url: https://graphsearch.epfl.ch/fr/concept/52198543

 47%|████▋     | 1382/2939 [08:00<07:30,  3.46it/s]

Failed to fetch https://gw.geneanet.org/comrade28?lang=en&n=anhalt+dessau&p=princess+bathildis+of: 403 Client Error: Forbidden for url: https://gw.geneanet.org/comrade28?lang=en&n=anhalt+dessau&p=princess+bathildis+of

 47%|████▋     | 1385/2939 [08:01<08:53,  2.91it/s]

Failed to fetch https://hancher.uiowa.edu/sites/hancher.uiowa.edu/files/soweto_gospel_choir_playbill_05_web.pdf: 404 Client Error: Not Found for url: https://hancher.uiowa.edu/Online/Article/sites/hancher.uiowa.edu/files/soweto_gospel_choir_playbill_05_web.pdf

 47%|████▋     | 1389/2939 [08:02<09:11,  2.81it/s]

Failed to fetch https://headsup.scoutlife.org/happy-birthday-to-bsa-legend-norman-rockwell/: 404 Client Error: Not Found for url: https://headsup.scoutlife.org/happy-birthday-to-bsa-legend-norman-rockwell/

 47%|████▋     | 1393/2939 [08:05<11:18,  2.28it/s]

Failed to fetch https://hikinginthesmokys.com/linville-gorge-wilderness-area/: 404 Client Error: Not Found for url: https://hikinginthesmokys.com/linville-gorge-wilderness-area/
Failed to fetch https://historicengland.org.uk/advice/planning/contested-heritage/reinterpreting-heritage/case-study-commemorative-plaque-all-souls-college-library-oxford/: 403 Client Error: Forbidden for url: https://historicengland.org.uk/advice/planning/contested-heritage/reinterpreting-heritage/case-study-commemorative-plaque-all-souls-college-library-oxford/

 48%|████▊     | 1397/2939 [08:05<04:41,  5.47it/s]

Failed to fetch https://historicengland.org.uk/listing/the-list/list-entry/1063662?section=official-list-entry: 403 Client Error: Forbidden for url: https://historicengland.org.uk/listing/the-list/list-entry/1063662?section=official-list-entry
Failed to fetch https://historicengland.org.uk/listing/the-list/list-entry/1090695: 403 Client Error: Forbidden for url: https://historicengland.org.uk/listing/the-list/list-entry/1090695
Failed to fetch https://historicengland.org.uk/listing/the-list/list-entry/1090695?section=official-list-entry: 403 Client Error: Forbidden for url: https://historicengland.org.uk/listing/the-list/list-entry/1090695?section=official-list-entry
Failed to fetch https://historicengland.org.uk/listing/the-list/list-entry/1180136?section=official-list-entry: 403 Client Error: Forbidden for url: https://historicengland.org.uk/listing/the-list/list-entry/1180136?section=official-list-entry

 48%|████▊     | 1400/2939 [08:06<05:59,  4.28it/s]

Failed to fetch https://historicschools.org.za/view.asp?ItemID=2&tname=tblComponent3&oname=People&pg=front&subm=About: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

 48%|████▊     | 1404/2939 [08:08<12:23,  2.06it/s]

Failed to fetch https://hmdb.ca/metabolites/HMDB0014967: 403 Client Error: Forbidden for url: https://hmdb.ca/metabolites/HMDB0014967

 48%|████▊     | 1411/2939 [08:11<10:34,  2.41it/s]

Failed to fetch https://hometowntv12.ca/2023/11/30/brockville-museums-tbt-thursday-november-20-2023/: 406 Client Error: Not Acceptable for url: https://hometowntv12.ca/2023/11/30/brockville-museums-tbt-thursday-november-20-2023/
Failed to fetch https://hometowntv12.ca/2024/05/23/100-years-ago-brockville-cenotaph-was-unveiled/: 406 Client Error: Not Acceptable for url: https://hometowntv12.ca/2024/05/23/100-years-ago-brockville-cenotaph-was-unveiled/

 48%|████▊     | 1419/2939 [11:57<7:02:24, 16.67s/it]

Failed to fetch https://ieeexplore.ieee.org/author/37089882273: 418 Client Error: Unknown Code for url: https://ieeexplore.ieee.org/author/37089882273
Failed to fetch https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=6815800: 418 Client Error: Unknown Code for url: https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=6815800
Failed to fetch https://ifacca.org/news/2022/12/09/new-tool-moi-framework-helps-museums-increase-thei/: 403 Client Error: Forbidden for url: https://ifacca.org/news/2022/12/09/new-tool-moi-framework-helps-museums-increase-thei/
Failed to fetch https://iiab.me/kiwix/content/wikipedia_en_all_maxi_2023-10/A/Statue_of_Efra%C3%ADn_Gonz%C3%A1lez_Luna: 404 Client Error: Not Found for url: https://iiab.me/kiwix/content/wikipedia_en_all_maxi_2023-10/A/Statue_of_Efra%C3%ADn_Gonz%C3%A1lez_Luna

 48%|████▊     | 1422/2939 [11:59<3:29:10,  8.27s/it]

Failed to fetch https://imslp.org/wiki/Un%27_alma_innamorata: 404 Client Error: Not Found for url: https://imslp.org/wiki/Un%27_alma_innamorata

 48%|████▊     | 1425/2939 [12:00<1:32:18,  3.66s/it]

Failed to fetch https://in.hellomagazine.com/lifestyle/20231119303703/indian-cricket-lesser-known-facts/: 404 Client Error: Not Found for url: https://in.hellomagazine.com/lifestyle/20231119303703/indian-cricket-lesser-known-facts/

 49%|████▊     | 1426/2939 [12:01<1:12:17,  2.87s/it]

Failed to fetch https://indiaarchive.co/products/golden-tilla-palledar-hand-embroidered-pashmina-shawl-brown: 403 Client Error: Forbidden for url: http://ww38.indiaarchive.co/products/golden-tilla-palledar-hand-embroidered-pashmina-shawl-brown

 49%|████▊     | 1429/2939 [13:58<10:05:14, 24.05s/it]

Failed to fetch https://indiawris.gov.in/wiki/doku.php?id=chenab: HTTPSConnectionPool(host='indiawris.gov.in', port=443): Max retries exceeded with url: /wiki/doku.php?id=chenab (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f0287f898d0>, 'Connection to indiawris.gov.in timed out. (connect timeout=10)'))

 49%|████▊     | 1431/2939 [14:08<5:54:06, 14.09s/it]

Failed to fetch https://indiawris.gov.in/wiki/doku.php?id=kosi_basin: HTTPSConnectionPool(host='indiawris.gov.in', port=443): Max retries exceeded with url: /wiki/doku.php?id=kosi_basin (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02863eed50>, 'Connection to indiawris.gov.in timed out. (connect timeout=10)'))

 49%|████▉     | 1434/2939 [14:09<2:08:50,  5.14s/it]

Failed to fetch https://intermezzo.typepad.com/intermezzo/2007/07/oae.html: 403 Client Error: Forbidden for url: https://www.networksolutions.com/typepad?siteID=100&channelID=P99C100S653N0B5A1D0E0000V111

 49%|████▉     | 1435/2939 [14:10<1:35:52,  3.83s/it]

Failed to fetch https://internationalhockeywiki.com/ihw/index.php/1919-20_Memorial_Cup_Final: 406 Client Error: Not Acceptable for url: https://internationalhockeywiki.com/ihw/index.php/1919-20_Memorial_Cup_Final

 49%|████▉     | 1437/2939 [14:11<51:22,  2.05s/it]

Failed to fetch https://islamforwest.org/2012/01/04/andrew-dickson-white-author-of-a-history-of-the-warfare-of-science-with-theology-in-christendom/: 410 Client Error: Gone for url: https://islamforwest.org/2012/01/04/andrew-dickson-white-author-of-a-history-of-the-warfare-of-science-with-theology-in-christendom/

 49%|████▉     | 1441/2939 [14:22<51:43,  2.07s/it]

Failed to fetch https://itihasaa.com/ranas/dev-shumsher/: 404 Client Error: Not Found for url: https://itihasaa.com/ranas/dev-shumsher/

 49%|████▉     | 1442/2939 [14:23<40:19,  1.62s/it]

Failed to fetch https://jkarchives.nic.in/Museum_Jammu.htm: HTTPSConnectionPool(host='jkarchives.nic.in', port=443): Max retries exceeded with url: /Museum_Jammu.htm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0289c8f710>: Failed to establish a new connection: [Errno -2] Name or service not known'))

 49%|████▉     | 1446/2939 [14:34<1:02:56,  2.53s/it]

Failed to fetch https://jnnp.bmj.com/content/83/2/188: 403 Client Error: Forbidden for url: https://jnnp.bmj.com/content/83/2/188

 49%|████▉     | 1447/2939 [14:35<48:57,  1.97s/it]

Failed to fetch https://jodytinsight.s3.rbx.io.cloud.ovh.net/ritesh-batra-height-weight-family-facts-spouse.html: 404 Client Error: Not Found for url: https://jodytinsight.s3.rbx.io.cloud.ovh.net/ritesh-batra-height-weight-family-facts-spouse.html

 49%|████▉     | 1449/2939 [14:36<29:21,  1.18s/it]

Failed to fetch https://johncage.org/pp/John-Cage-Work-Detail.cfm?work_ID=228: 404 Client Error: Not Found for url: https://johncage.org/pp/John-Cage-Work-Detail.cfm?work_ID=228

 50%|████▉     | 1466/2939 [14:55<26:44,  1.09s/it]

Failed to fetch https://kelas-wiraswasta-mm-stimaimmi.kpt.co.id/IT/en/131-2/Stanford-University-centers-and-institutes_21778_kelas-wiraswasta-mm-stimaimmi-kpt.html: 403 Client Error: Forbidden for url: https://kelas-wiraswasta-mm-stimaimmi.kpt.co.id/IT/en/131-2/Stanford-University-centers-and-institutes_21778_kelas-wiraswasta-mm-stimaimmi-kpt.html
Failed to fetch https://kerembeyit.artstation.com/resume: 403 Client Error: Forbidden for url: https://kerembeyit.artstation.com/resume

 51%|█████     | 1498/2939 [15:08<07:45,  3.10it/s]

Failed to fetch https://lapada.org/art-and-antiques/antique-oil-painting-manner-of-jean-antoine-watteau-the-serenade-early-19th-c/: 403 Client Error: Forbidden for url: https://lapada.org/art-and-antiques/antique-oil-painting-manner-of-jean-antoine-watteau-the-serenade-early-19th-c/

 52%|█████▏    | 1520/2939 [16:22<56:50,  2.40s/it]

Failed to fetch https://m.kpt.co.id/IT/en/105-2/Vint-Cerf_16065_m-kpt.html: 403 Client Error: Forbidden for url: https://m.kpt.co.id/IT/en/105-2/Vint-Cerf_16065_m-kpt.html
Failed to fetch https://mae.ucdavis.edu/news/raissa-dsouza-appointed-lead-editor-physical-review-research: 403 Client Error: Forbidden for url: https://mae.ucdavis.edu/news/raissa-dsouza-appointed-lead-editor-physical-review-research

 52%|█████▏    | 1525/2939 [16:49<1:40:17,  4.26s/it]

Failed to fetch https://manualredeye.com/95964/arts-entertainment/how-journalist-belva-davis-reported-her-way-to-success/: 403 Client Error: Forbidden for url: https://manualredeye.com/95964/arts-entertainment/how-journalist-belva-davis-reported-her-way-to-success/

 52%|█████▏    | 1527/2939 [16:57<1:31:01,  3.87s/it]

Failed to fetch https://mapcarta.com/13313466: 403 Client Error: Forbidden for url: https://mapcarta.com/13313466

 53%|█████▎    | 1546/2939 [17:05<07:26,  3.12it/s]

Failed to fetch https://me.engin.umich.edu/news-events/news/ulsoy-receives-asme-charles-russ-richards-award/: 403 Client Error: Forbidden for url: https://me.engin.umich.edu/news-events/news/ulsoy-receives-asme-charles-russ-richards-award/
Failed to fetch https://media.al.com/mcolurso/other/101HANKTREE.pdf: 403 Client Error: Forbidden for url: https://media.al.com/mcolurso/other/101HANKTREE.pdf

 53%|█████▎    | 1555/2939 [17:10<07:55,  2.91it/s]

Failed to fetch https://medium.com/@Samuel.kerr/im-still-around-32db1572765a: 403 Client Error: Forbidden for url: https://medium.com/@Samuel.kerr/im-still-around-32db1572765a
Failed to fetch https://medium.com/@bhaskaravsupraja/ever-heard-of-vampire-numbers-ac45830315a1: 403 Client Error: Forbidden for url: https://medium.com/@bhaskaravsupraja/ever-heard-of-vampire-numbers-ac45830315a1
Failed to fetch https://medium.com/@soodsandeep/the-queen-of-carnatic-music-ms-subbulakshmi-1bef3f1a3533: 403 Client Error: Forbidden for url: https://medium.com/@soodsandeep/the-queen-of-carnatic-music-ms-subbulakshmi-1bef3f1a3533
Failed to fetch https://medium.com/meet-meenamma/story-of-the-himalayan-hero-sonam-wangchuk-5c1a08a0d771: 403 Client Error: Forbidden for url: https://medium.com/meet-meenamma/story-of-the-himalayan-hero-sonam-wangchuk-5c1a08a0d771
Failed to fetch https://memim.com/2003-asian-badminton-championships.html: Exceeded 30 redirects.

 53%|█████▎    | 1562/2939 [17:15<10:21,  2.22it/s]

Failed to fetch https://milenaolesinska77.medium.com/exposition-art-blog-art-fashion-junya-watanabe-5573f2dfe84c: 403 Client Error: Forbidden for url: https://milenaolesinska77.medium.com/exposition-art-blog-art-fashion-junya-watanabe-5573f2dfe84c

 53%|█████▎    | 1566/2939 [17:27<1:07:45,  2.96s/it]

Failed to fetch https://mojim.com/usy100727x2x10.htm: HTTPSConnectionPool(host='mojim.com', port=443): Max retries exceeded with url: /usy100727x2x10.htm (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f02881d7190>, 'Connection to mojim.com timed out. (connect timeout=10)'))
Failed to fetch https://money.cnn.com/2016/12/06/technology/instagram-turn-off-comments/index.html: 503 Server Error: No healthy IP available for the backend for url: https://money.cnn.com/2016/12/06/technology/instagram-turn-off-comments/index.html

 54%|█████▎    | 1573/2939 [17:30<16:18,  1.40it/s]

Failed to fetch https://music.metason.net/artistinfo?name=Robert%20Patrick%20Weston: HTTPSConnectionPool(host='music.metason.net', port=443): Max retries exceeded with url: /artistinfo?name=Robert%20Patrick%20Weston (Caused by SSLError(CertificateError("hostname 'music.metason.net' doesn't match either of '*.hosttech.eu', 'hosttech.eu'")))

 54%|█████▎    | 1576/2939 [17:30<07:59,  2.84it/s]

Failed to fetch https://music.metason.net/artistinfo?name=Stefan%20Parkman: HTTPSConnectionPool(host='music.metason.net', port=443): Max retries exceeded with url: /artistinfo?name=Stefan%20Parkman (Caused by SSLError(CertificateError("hostname 'music.metason.net' doesn't match either of '*.hosttech.eu', 'hosttech.eu'")))
Failed to fetch https://musicstax.com/track/i-offer-my-life/37rdS9bf283vPI40AfYu43: 403 Client Error: Forbidden for url: https://musicstax.com/track/i-offer-my-life/37rdS9bf283vPI40AfYu43

 54%|█████▎    | 1577/2939 [17:30<06:42,  3.38it/s]

Failed to fetch https://mx-schroeder.medium.com/watery-ways-the-1918-weesp-netherlands-train-derailment-06b2b5b1fe27: 403 Client Error: Forbidden for url: https://mx-schroeder.medium.com/watery-ways-the-1918-weesp-netherlands-train-derailment-06b2b5b1fe27

 54%|█████▍    | 1581/2939 [17:32<07:43,  2.93it/s]

Failed to fetch https://myinfo.com.gh/2022/07/statues-of-ghana-the-asantehene-who-maintained-a-good-relationship-between-acheampong-rawlings/: HTTPSConnectionPool(host='myinfo.com.gh', port=443): Max retries exceeded with url: /2022/07/statues-of-ghana-the-asantehene-who-maintained-a-good-relationship-between-acheampong-rawlings/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f02856f6a90>: Failed to establish a new connection: [Errno -2] Name or service not known'))

 54%|█████▍    | 1586/2939 [17:35<10:22,  2.17it/s]

Failed to fetch https://nation.africa/kenya/news/politics/former-kanu-strong-man-kamotho-dies-1049656: 403 Client Error: Forbidden for url: https://nation.africa/kenya/news/politics/former-kanu-strong-man-kamotho-dies-1049656
Failed to fetch https://nation.africa/kenya/news/the-life-and-times-of-nicholas-biwott-423352: 403 Client Error: Forbidden for url: https://nation.africa/kenya/news/the-life-and-times-of-nicholas-biwott-423352
Failed to fetch https://nationalinterest.org/blog/buzz/kazakhstan-not-russia-was-last-republic-leave-ussr-195400: 403 Client Error: Forbidden for url: https://nationalinterest.org/blog/buzz/kazakhstan-not-russia-was-last-republic-leave-ussr-195400

 54%|█████▍    | 1589/2939 [17:36<08:19,  2.70it/s]

Failed to fetch https://naturehabitats.org/?rdp_we_resource=https%3A%2F%2Fen.wikipedia.org%2Fw%2Findex.php%3Ftitle%3DPyotr_Kapitsa%26diff%3Dprev%26oldid%3D311439504: 401 Client Error: Unauthorized for url: https://naturehabitats.org/?rdp_we_resource=https%3A%2F%2Fen.wikipedia.org%2Fw%2Findex.php%3Ftitle%3DPyotr_Kapitsa%26diff%3Dprev%26oldid%3D311439504

 54%|█████▍    | 1592/2939 [17:40<25:11,  1.12s/it]

Failed to fetch https://nepalpeakadventure.com/how-tall-is-mount-everest/: 406 Client Error: Not Acceptable for url: https://nepalpeakadventure.com/how-tall-is-mount-everest/

 54%|█████▍    | 1597/2939 [17:43<13:33,  1.65it/s]

Failed to fetch https://nhm.gov.in/New-Update-2022-24/CH-Programmes/Resource-Material-MusQan/Musqan-JNS.pdf: HTTPSConnectionPool(host='nhm.gov.in', port=443): Max retries exceeded with url: /New-Update-2022-24/CH-Programmes/Resource-Material-MusQan/Musqan-JNS.pdf (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1016)')))

 55%|█████▍    | 1610/2939 [19:21<7:41:29, 20.84s/it]

Failed to fetch https://nz.datescloud.com/rose-matafeo-and-guy-montgomerys-tiny-tour-of-aotearoa-2020-the-meteor-hamilton-2027453-302617275.html: HTTPSConnectionPool(host='nz.datescloud.com', port=443): Max retries exceeded with url: /rose-matafeo-and-guy-montgomerys-tiny-tour-of-aotearoa-2020-the-meteor-hamilton-2027453-302617275.html (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f0289203f90>, 'Connection to nz.datescloud.com timed out. (connect timeout=10)'))

 55%|█████▌    | 1621/2939 [19:26<20:39,  1.06it/s]

Failed to fetch https://olympics.com/en/athletes/aizanat-murtazaeva: 403 Client Error: Forbidden for url: https://olympics.com/en/athletes/aizanat-murtazaeva
Failed to fetch https://olympics.com/en/athletes/andrea-borella: 403 Client Error: Forbidden for url: https://olympics.com/en/athletes/andrea-borella
Failed to fetch https://olympics.com/en/athletes/frederick-william-macmonnies: 403 Client Error: Forbidden for url: https://olympics.com/en/athletes/frederick-william-macmonnies
Failed to fetch https://olympics.com/en/olympic-games/melbourne-1956/medals: 403 Client Error: Forbidden for url: https://olympics.com/en/olympic-games/melbourne-1956/medals
Failed to fetch https://olympics.com/en/olympic-games/sydney-2000/results/swimming/400m-individual-medley-men: 403 Client Error: Forbidden for url: https://olympics.com/en/olympic-games/sydney-2000/results/swimming/400m-individual-medley-men
Failed to fetch https://olympics.com/en/olympic-games/tokyo-2020/results/fencing/women-s-epee-team: 403 Client Error: Forbidden for url: https://olympics.com/en/olympic-games/tokyo-2020/results/fencing/women-s-epee-team

 55%|█████▌    | 1624/2939 [19:27<13:05,  1.67it/s]

Failed to fetch https://onlinelibrary.wiley.com/doi/10.1002/aisy.202300131: 403 Client Error: Forbidden for url: https://onlinelibrary.wiley.com/doi/10.1002/aisy.202300131
Failed to fetch https://onlinelibrary.wiley.com/doi/full/10.1002/aisy.202300131: 403 Client Error: Forbidden for url: https://onlinelibrary.wiley.com/doi/full/10.1002/aisy.202300131

 55%|█████▌    | 1626/2939 [19:28<12:55,  1.69it/s]

Failed to fetch https://oregonsportshall.org/timeline/alfred-a-c-gilbert-track-field/: 404 Client Error: Not Found for url: https://oregonsportshall.org/timeline/alfred-a-c-gilbert-track-field/

 55%|█████▌    | 1627/2939 [19:29<12:38,  1.73it/s]

Failed to fetch https://oroagri.eu/FxE4Wt2tv: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

 55%|█████▌    | 1629/2939 [19:32<22:11,  1.02s/it]

Failed to fetch https://p2k.stekom.ac.id/ensiklopedia/Pemilihan_umum_Presiden_Prancis_1958: 403 Client Error: Forbidden for url: https://p2k.stekom.ac.id/ensiklopedia/Pemilihan_umum_Presiden_Prancis_1958

 55%|█████▌    | 1630/2939 [19:33<19:30,  1.12it/s]

Failed to fetch https://pagesweturned.medium.com/a-post-so-bad-it-cant-be-ignored-c879abfa08a6: 403 Client Error: Forbidden for url: https://pagesweturned.medium.com/a-post-so-bad-it-cant-be-ignored-c879abfa08a6

 56%|█████▌    | 1635/2939 [19:34<08:36,  2.53it/s]

Failed to fetch https://parklore.com/main/top-thrill-dragster/3/: 406 Client Error: Not Acceptable for url: https://parklore.com/main/top-thrill-dragster/3/

 56%|█████▌    | 1642/2939 [19:48<1:14:20,  3.44s/it]

Failed to fetch https://pastpresidentsofindia.indiapress.org/reddy.html: HTTPSConnectionPool(host='pastpresidentsofindia.indiapress.org', port=443): Read timed out. (read timeout=10)

 56%|█████▌    | 1651/2939 [19:51<07:46,  2.76it/s]

Failed to fetch https://pem.as.atlas-sys.com/repositories/2/archival_objects/10032: 403 Client Error: Forbidden for url: https://pem.as.atlas-sys.com/repositories/2/archival_objects/10032
Failed to fetch https://pendium.fandom.com/wiki/Barry_Goldwater: 404 Client Error: Not Found for url: https://pendium.fandom.com/wiki/Barry_Goldwater

 57%|█████▋    | 1663/2939 [20:25<1:11:18,  3.35s/it]

Failed to fetch https://pikaialodge.com/: HTTPSConnectionPool(host='pikaialodge.com', port=443): Read timed out. (read timeout=10)

 57%|█████▋    | 1670/2939 [20:30<20:45,  1.02it/s]

Failed to fetch https://portal.stf.jus.br/ministro/presidente.asp?periodo=stj&id=240: HTTPSConnectionPool(host='portal.stf.jus.br', port=443): Max retries exceeded with url: /ministro/presidente.asp?periodo=stj&id=240 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1016)')))

 57%|█████▋    | 1672/2939 [20:31<13:03,  1.62it/s]

Failed to fetch https://pothashang.in/2017/06/lok-sabha-speaker-inaugurate-16th-nercpa-conference-imphal/: 404 Client Error: Not Found for url: https://pothashang.in/2017/06/lok-sabha-speaker-inaugurate-16th-nercpa-conference-imphal/

 58%|█████▊    | 1690/2939 [20:36<06:28,  3.22it/s]

Failed to fetch https://progressiveartistsgroup.com/progressive-artists-group-manishi-dey/: HTTPSConnectionPool(host='progressiveartistsgroup.com', port=443): Max retries exceeded with url: /progressive-artists-group-manishi-dey/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0288073ed0>: Failed to establish a new connection: [Errno -2] Name or service not known'))

 58%|█████▊    | 1701/2939 [20:49<1:00:33,  2.93s/it]

Failed to fetch https://pulsemusic.proboards.com/thread/182815/pulse-rankdown-1997-active-chart?page=7: HTTPSConnectionPool(host='pulsemusic.proboards.com', port=443): Read timed out. (read timeout=10)

 58%|█████▊    | 1707/2939 [21:05<29:54,  1.46s/it]

Failed to fetch https://radiostationwika.fandom.com/wiki/KTCZ: 404 Client Error: Not Found for url: https://radiostationwika.fandom.com/wiki/KTCZ

 58%|█████▊    | 1709/2939 [21:05<19:11,  1.07it/s]

Failed to fetch https://radiotoday.co.uk/2013/09/radio-wales-louise-elliott-takes-a-break/: 500 Server Error: Internal Server Error for url: https://radiotoday.co.uk/2013/09/radio-wales-louise-elliott-takes-a-break/
Failed to fetch https://rateyourmusic.com/artist/band-of-joy: 403 Client Error: Forbidden for url: https://rateyourmusic.com/artist/band-of-joy

 58%|█████▊    | 1713/2939 [21:06<07:28,  2.74it/s]

Failed to fetch https://rateyourmusic.com/release/album/johnny_rivers/rewind/: 403 Client Error: Forbidden for url: https://rateyourmusic.com/release/album/johnny_rivers/rewind/
Failed to fetch https://rateyourmusic.com/release/album/nomeansno/why-do-they-call-me-mr-happy/: 403 Client Error: Forbidden for url: https://rateyourmusic.com/release/album/nomeansno/why-do-they-call-me-mr-happy/
Failed to fetch https://rateyourmusic.com/release/ep/avenger/depraved-to-black.p/: 403 Client Error: Forbidden for url: https://rateyourmusic.com/release/ep/avenger/depraved-to-black.p/
Failed to fetch https://rateyourmusic.com/release/unauth/stewart-copeland/spyro-enter-the-dragonfly/: 403 Client Error: Forbidden for url: https://rateyourmusic.com/release/unauth/stewart-copeland/spyro-enter-the-dragonfly/

 58%|█████▊    | 1715/2939 [21:06<05:17,  3.86it/s]

Failed to fetch https://rebrickable.com/search/?show_printed=on&include_accessory=1&include_gear=1&q=4178&search_type=all: 403 Client Error: Forbidden for url: https://rebrickable.com/search/?show_printed=on&include_accessory=1&include_gear=1&q=4178&search_type=all

 58%|█████▊    | 1717/2939 [21:07<06:39,  3.06it/s]

Failed to fetch https://reidhall.globalcenters.columbia.edu/macmonnies: 403 Client Error: Forbidden for url: https://reidhall.globalcenters.columbia.edu/macmonnies

 59%|█████▊    | 1723/2939 [21:14<21:45,  1.07s/it]

Failed to fetch https://results.finishtime.co.za/results.aspx?CId=35&RId=30350&EId=1&dt=0&so=1&st=sL0P6hT17GLleRsNVn9WeQ3DvvGYdQhgYyrdMCyXuj5xbqkfgZjrgH6DkEiqalOh: 403 Client Error: Forbidden for url: https://results.finishtime.co.za/results.aspx?CId=35&RId=30350&EId=1&dt=0&so=1&st=sL0P6hT17GLleRsNVn9WeQ3DvvGYdQhgYyrdMCyXuj5xbqkfgZjrgH6DkEiqalOh

 59%|█████▉    | 1730/2939 [21:21<16:18,  1.24it/s]

Failed to fetch https://rochesteravionicarchives.co.uk/platforms/harrier: 404 Client Error: Not Found for url: https://rochesteravionicarchives.co.uk/platforms/harrier

 59%|█████▉    | 1737/2939 [21:30<16:08,  1.24it/s]

Failed to fetch https://rugbyreferee.net/2019/05/07/2019-rugby-world-cup-referees-announced/: 406 Client Error: Not Acceptable for url: https://rugbyreferee.net/2019/05/07/2019-rugby-world-cup-referees-announced/

 59%|█████▉    | 1741/2939 [21:32<10:19,  1.93it/s]

Failed to fetch https://sas.org.in/our-mentors/: 404 Client Error: Not Found for url: https://sas.org.in/our-mentors/

 59%|█████▉    | 1745/2939 [21:33<06:30,  3.06it/s]

Failed to fetch https://scitechdaily.com/bionic-breakthrough-revolutionary-self-sensing-electric-artificial-muscles/: 403 Client Error: Forbidden for url: https://scitechdaily.com/bionic-breakthrough-revolutionary-self-sensing-electric-artificial-muscles/

 60%|█████▉    | 1750/2939 [21:34<04:18,  4.60it/s]

Failed to fetch https://screenrant.com/dungeons-dragons-new-subclass-returning-tasha-cauldron-everything/: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Failed to fetch https://search.worldcat.org/es/title/dialoghi-di-archeologia/oclc/3799006: 403 Client Error: Forbidden for url: https://search.worldcat.org/es/title/dialoghi-di-archeologia/oclc/3799006
Failed to fetch https://secondhandsongs.com/performance/59985/all: 403 Client Error: Forbidden for url: https://secondhandsongs.com/performance/59985/all

 60%|██████    | 1771/2939 [21:46<04:43,  4.12it/s]

Failed to fetch https://spaceagechronicle.com/iconic-building-remains-a-pillar-of-americas-spaceport/: 406 Client Error: Not Acceptable for url: https://spaceagechronicle.com/iconic-building-remains-a-pillar-of-americas-spaceport/

 60%|██████    | 1773/2939 [21:47<07:50,  2.48it/s]

Failed to fetch https://sports.ndtv.com/cricket/kkr-vs-srh-scorecard-live-cricket-score-ipl-2019-match-2-krsh03242019189311: 403 Client Error: Forbidden for url: https://sports.ndtv.com/cricket/kkr-vs-srh-scorecard-live-cricket-score-ipl-2019-match-2-krsh03242019189311

 61%|██████    | 1779/2939 [22:24<2:08:18,  6.64s/it]

Failed to fetch https://steamdb.info/patchnotes/11140647/: 403 Client Error: Forbidden for url: https://steamdb.info/patchnotes/11140647/

 61%|██████    | 1782/2939 [22:35<1:46:48,  5.54s/it]

Failed to fetch https://stokveltalk.co.za/kaizer-chiefs-take-it-all-at-the-shell-helix-ultra-cup-2019/: HTTPSConnectionPool(host='stokveltalk.co.za', port=443): Read timed out. (read timeout=10)

 61%|██████    | 1791/2939 [22:47<15:28,  1.24it/s]

Failed to fetch https://teara.govt.nz/en/artwork/35391/powerhouse-tuai-1948: 403 Client Error: Forbidden for url: https://teara.govt.nz/en/artwork/35391/powerhouse-tuai-1948

 61%|██████▏   | 1802/2939 [22:51<07:52,  2.41it/s]

Failed to fetch https://thebookerprizes.com/the-booker-library/judges/stella-rimington: 403 Client Error: Forbidden for url: https://thebookerprizes.com/the-booker-library/judges/stella-rimington

 61%|██████▏   | 1804/2939 [22:52<07:45,  2.44it/s]

Failed to fetch https://thecognate.com/shaikh-mishary-bin-rashid-alafasy/: 404 Client Error: Not Found for url: https://thecognate.com/shaikh-mishary-bin-rashid-alafasy/

 62%|██████▏   | 1812/2939 [23:09<1:06:24,  3.54s/it]

Failed to fetch https://thenorthyorkshiregallery.co.uk/199-steps/: HTTPSConnectionPool(host='thenorthyorkshiregallery.co.uk', port=443): Read timed out. (read timeout=10)

 62%|██████▏   | 1815/2939 [23:10<27:09,  1.45s/it]

Failed to fetch https://thereaderweb.com/?url=https://thereaderwiki.com/en/List%20of%20most%20expensive%20paintings: 502 Server Error: Bad Gateway for url: https://thereaderweb.com/?url=https://thereaderwiki.com/en/List%20of%20most%20expensive%20paintings

 62%|██████▏   | 1821/2939 [23:13<12:45,  1.46it/s]

Failed to fetch https://thevogue.com/artists/cannibal-corpse/: 404 Client Error: Not Found for url: https://www.thevogue.com/artists/cannibal-corpse

 63%|██████▎   | 1841/2939 [23:29<14:19,  1.28it/s]

Failed to fetch https://trak.in/tags/business/2007/07/26/top-50-web10-web-sites-of-india/: 404 Client Error: Not Found for url: https://trak.in/tags/business/2007/07/26/top-50-web10-web-sites-of-india/

 63%|██████▎   | 1845/2939 [23:29<07:23,  2.46it/s]

Failed to fetch https://tsort.info/music/cxhcuc.htm: HTTPSConnectionPool(host='tsort.info', port=443): Max retries exceeded with url: /music/cxhcuc.htm (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1016)')))
Failed to fetch https://tt.tennis-warehouse.com/index.php?threads/arthur-w-myers-%E2%80%93-a-testament-to-tennis.576159/: HTTPSConnectionPool(host='tt.tennis-warehouse.com', port=443): Max retries exceeded with url: /index.php?threads/arthur-w-myers-%E2%80%93-a-testament-to-tennis.576159/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1016)')))

 63%|██████▎   | 1848/2939 [23:30<05:42,  3.18it/s]

Failed to fetch https://tvtropes.org/pmwiki/pmwiki.php/Recap/MotherlandFortSalemS1E10Witchbomb: 403 Client Error: Forbidden for url: https://tvtropes.org/pmwiki/pmwiki.php/Recap/MotherlandFortSalemS1E10Witchbomb

 63%|██████▎   | 1850/2939 [23:41<56:27,  3.11s/it]

Failed to fetch https://uct.ac.za/radio/articles/2019-04-01-cape-town-international-jazz-festival-2019: HTTPSConnectionPool(host='uct.ac.za', port=443): Read timed out. (read timeout=10)

 63%|██████▎   | 1855/2939 [23:44<18:02,  1.00it/s]

Failed to fetch https://ultiworld.com/2014/10/14/johnny-bravo-nationals-preview/: 403 Client Error: Forbidden for url: https://ultiworld.com/2014/10/14/johnny-bravo-nationals-preview/
Failed to fetch https://ultiworld.com/livewire/2014-denver-johnny-bravo-roster/: 403 Client Error: Forbidden for url: https://ultiworld.com/livewire/2014-denver-johnny-bravo-roster/

 63%|██████▎   | 1861/2939 [23:49<13:28,  1.33it/s]

Failed to fetch https://unesdoc.unesco.org/ark:/48223/pf0000377433?posInSet=4&queryId=N-8f4956bb-3b56-4989-8ed8-2c49e7c6158b: 403 Client Error: Forbidden for url: https://unesdoc.unesco.org/ark:/48223/pf0000377433?posInSet=4&queryId=N-8f4956bb-3b56-4989-8ed8-2c49e7c6158b

 63%|██████▎   | 1863/2939 [23:49<08:43,  2.06it/s]

Failed to fetch https://universitylands.ua.edu/bryce-hospital: 404 Client Error: Not Found for url: https://universitylands.ua.edu/bryce-hospital

 64%|██████▎   | 1869/2939 [24:01<18:29,  1.04s/it]

Failed to fetch https://useum.org/artwork/All-my-Kingdoms-Cover-Kerem-Beyit-2013: 403 Client Error: Forbidden for url: https://www.useum.org/artwork/All-my-Kingdoms-Cover-Kerem-Beyit-2013

 64%|██████▍   | 1878/2939 [24:08<11:51,  1.49it/s]

Failed to fetch https://ville.saguenay.ca/files/activites_et_loisirs/histoire_et_patrimoine/batiments_et_lieux_d_interet/jonquiere/16_le_theatre_palace_arvida.pdf: 404 Client Error: Not Found for url: https://ville.saguenay.ca/files/activites_et_loisirs/histoire_et_patrimoine/batiments_et_lieux_d_interet/jonquiere/16_le_theatre_palace_arvida.pdf

 64%|██████▍   | 1880/2939 [24:09<08:57,  1.97it/s]

Failed to fetch https://vinyl-records.nl/power-speed-metal/blind-guardian-vinyl-discography-and-album-covers-from-1989-1990.html: 404 Client Error: Not Found for url: https://vinyl-records.nl/power-speed-metal/blind-guardian-vinyl-discography-and-album-covers-from-1989-1990.html

 64%|██████▍   | 1882/2939 [24:09<06:48,  2.59it/s]

Failed to fetch https://voiceactorsplacesmediaandmore.fandom.com/wiki/Rosie_Perez: 410 Client Error: Gone for url: https://voiceactorsplacesmediaandmore.fandom.com/wiki/Rosie_Perez

 64%|██████▍   | 1884/2939 [24:10<05:45,  3.06it/s]

Failed to fetch https://voltzclarke.com/artists/uzo-njoku/bio/: 404 Client Error: Not Found for url: https://voltzclarke.com/artists/uzo-njoku/bio/

 64%|██████▍   | 1887/2939 [24:10<03:47,  4.63it/s]

Failed to fetch https://watermark.silverchair.com/493_1.pdf?token=AQECAHi208BE49Ooan9kkhW_Ercy7Dm3ZL_9Cf3qfKAc485ysgAABGAwggRcBgkqhkiG9w0BBwagggRNMIIESQIBADCCBEIGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMvegxpaLqdbE_YqFiAgEQgIIEExwkQFNwsKOV8IWn1_Ph1kRUgo9CDJYdKtVmb2O86ntfitIs5dZkJas0rBsVfBxYAOSe5jWXvAquk-zndamvgLUp4zyHdfAbqc5dVvgziFkrmVyQyDPQygh609I8Gsjg6jWTP-3RChfRP0yDcmJMMMqSvxpKNNSwHPi-kMFVDVMgF0efOowaHBXtpoNTMz0tRna4gQDIOvs6jKlX-L025zNTtQ7yGRy8aTPT7P-MvTWTVq7hr3Nuv4o9gcc7e0dLwmDWScm6MLWRQ6BBdpkNPOJLMmL_0gvHE4NaOjbGsY7ClreUmW_414sXIvIueWC3-eH9RSSzWK57BGnG9qYUftRNWe5lDXVBetwLNBe0Hk4pdj4OWHyhl7KLs_NPcxKf4j2Vb_9VRsNtH_dcPcVGNwAD8NTEnSIDQZuYXezus8NXDplNhAUKaVUoGsIId86fb05aMxLp7Qj5kg0U62WscfQVGc8x-6zhKinYCcR7UDShxA0VYAjjlp5qzifR4MPbw8P-TadLc9Ak_naStJ2R3EtsHTG6-kaOju9CsFKtV-L5-ufUtel_KQFfvBEV8ArOK5dOpp3LO0gzFsBZELKfHfk4aC88SQdUicVZakrfjYEm_ODscjEDokQeu2G9mb_4PKS8VXMEDM6a49dv7reLyG97yA2s6FfahF7PpjgmDU-5T5M3UYi3fmDnsDbbs91OHnI0Z3eBNnWfCVNuNMqlkeb5l9ML7zgkTqPX1Zrd0fs-BqQ-QevgKSy4tpXw9K6pyc47S1FqM9TrdYiIU1pfCHHz_tPrCYbtBKuVBsJY4alhmoIdxeH9MrjUR2zaMzLA7DFzp4t4hk0cfIo_yp0tfxzcOASojsFI83xMGfspwTUXTjAkkcmEAwZJDPX0qxrlDjkeXjNUT_k7qhAIOuUFGCU0ZSIAx0Il2K4pNVLu5Pgi1vRMddBGtj8KgFr22wXb5Wl4T1uskI0k_e227zZe8Y-TFa5OyN5BxhQwa7g-TmiNfOx78MGhv-TPMZ_Mxkd9R82vYhCOb1N_pTJkdjvaXFF_3sz_1k7xSa1aL1IahIsmqvSD5zwzfBGkTlngw17dqmfayxAYdWcc-qiUS3pvOev93SSiGLzPT-gFWO6lmN2o9wP6MKbQ-NHtT9X-s4NK-cFxgV4mQg93TidtVNFGz-c9ggV90xcU8XWQfy02slUJuytC15mwMVDUFqNUi-tOof5sxGurimRfSNbl8LJ565rnNR-a3Cl9HWBM6nReQtxA5T-HmL02AxPPht44c5darqjky3EksZjaZzJHx0tdRJDSdyEDxao6B0RuZKp8jUGaiPzBdxnug87de2OXhO7TqnuYOL31OEOTVIkGVl3QsMNib_hhWkVpz-V-H-egVcA3JVGo: HTTPSConnectionPool(host='watermark.silverchair.com', port=443): Max retries exceeded with url: /493_1.pdf?token=AQECAHi208BE49Ooan9kkhW_Ercy7Dm3ZL_9Cf3qfKAc485ysgAABGAwggRcBgkqhkiG9w0BBwagggRNMIIESQIBADCCBEIGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMvegxpaLqdbE_YqFiAgEQgIIEExwkQFNwsKOV8IWn1_Ph1kRUgo9CDJYdKtVmb2O86ntfitIs5dZkJas0rBsVfBxYAOSe5jWXvAquk-zndamvgLUp4zyHdfAbqc5dVvgziFkrmVyQyDPQygh609I8Gsjg6jWTP-3RChfRP0yDcmJMMMqSvxpKNNSwHPi-kMFVDVMgF0efOowaHBXtpoNTMz0tRna4gQDIOvs6jKlX-L025zNTtQ7yGRy8aTPT7P-MvTWTVq7hr3Nuv4o9gcc7e0dLwmDWScm6MLWRQ6BBdpkNPOJLMmL_0gvHE4NaOjbGsY7ClreUmW_414sXIvIueWC3-eH9RSSzWK57BGnG9qYUftRNWe5lDXVBetwLNBe0Hk4pdj4OWHyhl7KLs_NPcxKf4j2Vb_9VRsNtH_dcPcVGNwAD8NTEnSIDQZuYXezus8NXDplNhAUKaVUoGsIId86fb05aMxLp7Qj5kg0U62WscfQVGc8x-6zhKinYCcR7UDShxA0VYAjjlp5qzifR4MPbw8P-TadLc9Ak_naStJ2R3EtsHTG6-kaOju9CsFKtV-L5-ufUtel_KQFfvBEV8ArOK5dOpp3LO0gzFsBZELKfHfk4aC88SQdUicVZakrfjYEm_ODscjEDokQeu2G9mb_4PKS8VXMEDM6a49dv7reLyG97yA2s6FfahF7PpjgmDU-5T5M3UYi3fmDnsDbbs91OHnI0Z3eBNnWfCVNuNMqlkeb5l9ML7zgkTqPX1Zrd0fs-BqQ-QevgKSy4tpXw9K6pyc47S1FqM9TrdYiIU1pfCHHz_tPrCYbtBKuVBsJY4alhmoIdxeH9MrjUR2zaMzLA7DFzp4t4hk0cfIo_yp0tfxzcOASojsFI83xMGfspwTUXTjAkkcmEAwZJDPX0qxrlDjkeXjNUT_k7qhAIOuUFGCU0ZSIAx0Il2K4pNVLu5Pgi1vRMddBGtj8KgFr22wXb5Wl4T1uskI0k_e227zZe8Y-TFa5OyN5BxhQwa7g-TmiNfOx78MGhv-TPMZ_Mxkd9R82vYhCOb1N_pTJkdjvaXFF_3sz_1k7xSa1aL1IahIsmqvSD5zwzfBGkTlngw17dqmfayxAYdWcc-qiUS3pvOev93SSiGLzPT-gFWO6lmN2o9wP6MKbQ-NHtT9X-s4NK-cFxgV4mQg93TidtVNFGz-c9ggV90xcU8XWQfy02slUJuytC15mwMVDUFqNUi-tOof5sxGurimRfSNbl8LJ565rnNR-a3Cl9HWBM6nReQtxA5T-HmL02AxPPht44c5darqjky3EksZjaZzJHx0tdRJDSdyEDxao6B0RuZKp8jUGaiPzBdxnug87de2OXhO7TqnuYOL31OEOTVIkGVl3QsMNib_hhWkVpz-V-H-egVcA3JVGo (Caused by SSLError(CertificateError("hostname 'watermark.silverchair.com' doesn't match either of '*.azurewebsites.net', '*.scm.azurewebsites.net', '*.sso.azurewebsites.net', '*.eastus-01.azurewebsites.net', '*.scm.eastus-01.azurewebsites.net', '*.sso.eastus-01.azurewebsites.net', '*.eastus.c.azurewebsites.net', '*.scm.eastus.c.azurewebsites.net', '*.sso.eastus.c.azurewebsites.net', '*.azure-mobile.net', '*.scm.azure-mobile.net'")))
Failed to fetch https://waymarking.com/waymarks/wm16KRM_Rossland_Miners_Hall_receives_national_recognition_Rossland_BC: 403 Client Error: Forbidden for url: https://waymarking.com/waymarks/wm16KRM_Rossland_Miners_Hall_receives_national_recognition_Rossland_BC

 65%|██████▍   | 1910/2939 [24:45<23:14,  1.36s/it]

Failed to fetch https://wehotimes.com/west-hollywood-hosts-first-q-con-for-lgbt-comic-book-fans/: 403 Client Error: Forbidden for url: https://wehotimes.com/west-hollywood-hosts-first-q-con-for-lgbt-comic-book-fans/

 65%|██████▌   | 1913/2939 [24:46<12:31,  1.37it/s]

Failed to fetch https://whitemountaincentralrr.com/history/railroad/: 406 Client Error: Not Acceptable for url: https://whitemountaincentralrr.com/history/railroad/

 65%|██████▌   | 1914/2939 [24:56<1:00:08,  3.52s/it]

Failed to fetch https://whitman-prod.unl.edu/criticism/current/anc.00155.html: HTTPSConnectionPool(host='whitman-prod.unl.edu', port=443): Max retries exceeded with url: /criticism/current/anc.00155.html (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f028b78c210>, 'Connection to whitman-prod.unl.edu timed out. (connect timeout=10)'))

 65%|██████▌   | 1918/2939 [25:00<26:15,  1.54s/it]

Failed to fetch https://wiki.edunitas.com/IT/en/114-10/MICRO-Information-Management-System_11455_eduNitas.html: 403 Client Error: Forbidden for url: https://wiki.andrafarm.com/IT/en/114-10/MICRO-Information-Management-System_11455_eduNitas.html

 65%|██████▌   | 1919/2939 [25:01<26:13,  1.54s/it]

Failed to fetch https://wikidocs.net/214063: 403 Client Error: Forbidden for url: https://wikidocs.net/214063

 65%|██████▌   | 1923/2939 [25:03<14:26,  1.17it/s]

Failed to fetch https://wikiless.copper.dedyn.io/wiki/%C3%89douard_Stephan?useskin=vector: 404 Client Error: Not Found for url: https://wikiless.copper.dedyn.io/wiki/%C3%89douard_Stephan?useskin=vector

 66%|██████▌   | 1944/2939 [25:07<05:09,  3.22it/s]

Failed to fetch https://wwpw.eclipsewise.com/solar/SEprime/1801-1900/SE1805Jan01Pprime.html: HTTPSConnectionPool(host='wwpw.eclipsewise.com', port=443): Max retries exceeded with url: /solar/SEprime/1801-1900/SE1805Jan01Pprime.html (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0288e3b750>: Failed to establish a new connection: [Errno -2] Name or service not known'))

 66%|██████▋   | 1951/2939 [25:14<14:16,  1.15it/s]

Failed to fetch https://www.abc-usa.org/lee-spitzer/: 404 Client Error: Not Found for url: https://www.abc-usa.org/lee-spitzer/

 66%|██████▋   | 1952/2939 [25:15<12:49,  1.28it/s]

Failed to fetch https://www.abc.net.au/news/2009-09-22/doctor-jailed-over-former-first-ladys-lipo-death/1437416): 404 Client Error: Not Found for url: https://www.abc.net.au/news/2009-09-22/doctor-jailed-over-former-first-ladys-lipo-death/1437416)

 67%|██████▋   | 1963/2939 [25:33<10:04,  1.61it/s]

Failed to fetch https://www.africa.upenn.edu/Country_Specific/Zamflag.html: 403 Client Error: Forbidden for url: https://www.africa.upenn.edu/Country_Specific/Zamflag.html

 67%|██████▋   | 1965/2939 [25:37<21:09,  1.30s/it]

Failed to fetch https://www.aimlexchange.com/search/wiki/page/Wion_Tv: 403 Client Error: Forbidden for url: https://www.aimlexchange.com/search/wiki/page/Wion_Tv

 67%|██████▋   | 1969/2939 [25:39<11:39,  1.39it/s]

Failed to fetch https://www.alfred.com/two5/p/98-EP67419/: 403 Client Error: Forbidden for url: https://www.alfred.com/two5/p/98-EP67419/

 67%|██████▋   | 1981/2939 [25:43<06:23,  2.50it/s]

Failed to fetch https://www.altonbaseball.com/custom_pages/98260/lloyd-hopkins-field: 404 Client Error: Not Found for url: https://www.altonbaseball.com/custom_pages/98260/lloyd-hopkins-field

 67%|██████▋   | 1983/2939 [25:44<07:24,  2.15it/s]

Failed to fetch https://www.americancityandcounty.com/2014/12/11/dc-is-alight-with-the-pillar-of-fire/: 403 Client Error: Forbidden for url: https://www.americancityandcounty.com/2014/12/11/dc-is-alight-with-the-pillar-of-fire/

 68%|██████▊   | 1986/2939 [25:44<04:30,  3.52it/s]

Failed to fetch https://www.americanillustration.org/pressRelease/NMAI_Press_3_27_07.html: 406 Client Error: Not Acceptable for url: https://www.americanillustration.org/pressRelease/NMAI_Press_3_27_07.html

 68%|██████▊   | 1988/2939 [25:45<04:02,  3.92it/s]

Failed to fetch https://www.americanmusicpreservation.com/sistermildred.htm: 406 Client Error: Not Acceptable for url: https://www.americanmusicpreservation.com/sistermildred.htm
Failed to fetch https://www.amherst.edu/news/news_releases/2003/10_2003/node/9417: 405 Client Error: Not Allowed for url: https://www.amherst.edu/news/news_releases/2003/10_2003/node/9417

 68%|██████▊   | 1992/2939 [25:47<10:55,  1.44it/s]

Failed to fetch https://www.andivi.com/glossary/computer-history-museum/: 410 Client Error: Gone for url: https://www.andivi.com/glossary/computer-history-museum/

 68%|██████▊   | 1993/2939 [25:48<10:39,  1.48it/s]

Failed to fetch https://www.angadcreations.com/all-you-need-to-know-about-tilla-embroidered-saree/?v=5fc810cf6260: 404 Client Error: Not Found for url: https://angadcreations.com/all-you-need-to-know-about-tilla-embroidered-saree?v=5fc810cf6260

 68%|██████▊   | 1997/2939 [25:51<11:52,  1.32it/s]

Failed to fetch https://www.aphafoundation.org/archambault-scholarship-campaign: 404 Client Error: Not Found for url: https://www.aphafoundation.org/archambault-scholarship-campaign

 68%|██████▊   | 2005/2939 [25:59<11:15,  1.38it/s]

Failed to fetch https://www.art.state.gov/personnel/norman_rockwell/: 404 Client Error: Not Found for url: https://www.art.state.gov/personnel/norman_rockwell/

 68%|██████▊   | 2010/2939 [26:01<06:25,  2.41it/s]

Failed to fetch https://www.artspace.com/magazine/art_101/book_report/phaidon-going-once-auction-record-breakers-54348: 404 Client Error: Not Found for url: https://www.phaidon.com/en-us/blogs/stories/phaidon-going-once-auction-record-breakers

 68%|██████▊   | 2013/2939 [26:02<07:08,  2.16it/s]

Failed to fetch https://www.asiansquash.org/resources/docs/PAST%20ASIAN%20SQUASH%20INDIVIDUAL%20CHAMPIONSHIPS.pdf: 404 Client Error: Not Found for url: https://www.asiansquash.org/resources/docs/PAST%20ASIAN%20SQUASH%20INDIVIDUAL%20CHAMPIONSHIPS.pdf

 69%|██████▊   | 2018/2939 [26:05<09:22,  1.64it/s]

Failed to fetch https://www.astronomy.com/science/web-extra-25-asteroids-to-spot-through-binoculars/: 403 Client Error: Forbidden for url: https://www.astronomy.com/science/web-extra-25-asteroids-to-spot-through-binoculars/

 69%|██████▊   | 2020/2939 [26:06<08:43,  1.75it/s]

Failed to fetch https://www.audio-technica.com/en-us/our-story: 403 Client Error: Forbidden for url: https://www.audio-technica.com/en-us/our-story

 69%|██████▉   | 2023/2939 [26:12<21:46,  1.43s/it]

Failed to fetch https://www.austrianphilately.com/statetreaty/kreisky.htm: 404 Client Error: Not Found for url: https://austrianphilately.com/statetreaty/kreisky.htm

 69%|██████▉   | 2034/2939 [26:16<08:48,  1.71it/s]

Failed to fetch https://www.beloit.edu/live/news/1080-science-center-named-for-sangers: 403 Client Error: Forbidden for url: https://www.beloit.edu/live/news/1080-science-center-named-for-sangers

 69%|██████▉   | 2035/2939 [26:16<07:38,  1.97it/s]

Failed to fetch https://www.beloit.edu/live/news/155-naming-the-science-center: 403 Client Error: Forbidden for url: https://www.beloit.edu/live/news/155-naming-the-science-center

 69%|██████▉   | 2036/2939 [26:19<15:59,  1.06s/it]

Failed to fetch https://www.benjaminpauljohnson.com/: HTTPSConnectionPool(host='www.benjaminpauljohnson.com', port=443): Max retries exceeded with url: / (Caused by SSLError(CertificateError("hostname 'www.benjaminpauljohnson.com' doesn't match 'benjaminpauljohnson.com'")))

 69%|██████▉   | 2038/2939 [26:19<09:42,  1.55it/s]

Failed to fetch https://www.besoccer.com/player/garrido-256256: 406 Client Error: Not Acceptable for url: https://www.besoccer.com/player/garrido-256256

 70%|██████▉   | 2043/2939 [26:21<05:46,  2.58it/s]

Failed to fetch https://www.bizjournals.com/albany/stories/2008/04/28/daily2.html: 403 Client Error: Forbidden for url: https://www.bizjournals.com/albany/stories/2008/04/28/daily2.html

 71%|███████   | 2077/2939 [26:43<49:21,  3.44s/it]

Failed to fetch https://www.britishcouncil.uz/en/programmes/arts/new-past/cornelia-parker: HTTPSConnectionPool(host='www.britishcouncil.uz', port=443): Read timed out. (read timeout=10)

 71%|███████   | 2082/2939 [26:47<15:54,  1.11s/it]

Failed to fetch https://www.business-standard.com/health/first-abdm-microsite-under-nha-100-microsites-project-launched-in-mizoram-123082300324_1.html: 403 Client Error: Forbidden for url: https://www.business-standard.com/health/first-abdm-microsite-under-nha-100-microsites-project-launched-in-mizoram-123082300324_1.html
Failed to fetch https://www.business-standard.com/india-news/from-boat-to-virat-kohli-why-is-canadian-singer-shubh-facing-backlash-123092000385_1.html: 403 Client Error: Forbidden for url: https://www.business-standard.com/india-news/from-boat-to-virat-kohli-why-is-canadian-singer-shubh-facing-backlash-123092000385_1.html

 71%|███████   | 2086/2939 [26:49<11:04,  1.28it/s]

Failed to fetch https://www.canonwatch.com/canon-introduces-two-new-uhdgc-2-3-inch-portable-zoom-lenses-for-4k-uhd-broadcast/: 403 Client Error: Forbidden for url: https://www.canonwatch.com/canon-introduces-two-new-uhdgc-2-3-inch-portable-zoom-lenses-for-4k-uhd-broadcast/

 71%|███████▏  | 2100/2939 [26:59<06:12,  2.25it/s]

Failed to fetch https://www.cbr.com/one-dnd-ardling-race-abilities-names/: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

 72%|███████▏  | 2102/2939 [27:00<07:05,  1.97it/s]

Failed to fetch https://www.cdjapan.co.jp/product/NEODAI-56727: 404 Client Error: Not Found for url: https://www.cdjapan.co.jp/product/NEODAI-56727

 72%|███████▏  | 2103/2939 [27:01<09:20,  1.49it/s]

Failed to fetch https://www.celebritynooz.com/Celebrity.aspx/Berlinda_Tolbert: HTTPSConnectionPool(host='www.celebritynooz.com', port=443): Max retries exceeded with url: /Celebrity.aspx/Berlinda_Tolbert (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f02877d62d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))

 72%|███████▏  | 2105/2939 [27:02<06:25,  2.16it/s]

Failed to fetch https://www.celebsagewiki.com/michaela-huebschle: 436 Client Error: status code 436 for url: https://www.celebsagewiki.com/michaela-huebschle

 72%|███████▏  | 2107/2939 [27:02<05:00,  2.77it/s]

Failed to fetch https://www.celebsagewiki.com/vujica-lazovic: 436 Client Error: status code 436 for url: https://www.celebsagewiki.com/vujica-lazovic
Failed to fetch https://www.census.gov/quickfacts/fact/table/US: 403 Client Error: Forbidden for url: https://www.census.gov/quickfacts/fact/table/US
Failed to fetch https://www.census.gov/quickfacts/fact/table/porthuroncitymichigan/PST040223: 403 Client Error: Forbidden for url: https://www.census.gov/quickfacts/fact/table/porthuroncitymichigan/PST040223

 72%|███████▏  | 2112/2939 [27:04<04:07,  3.34it/s]

Failed to fetch https://www.centrobotin.org/en/obra-carta/work-no-3209-amigos-2019-jardines-pereda/: HTTPSConnectionPool(host='www.centrobotin.org', port=443): Max retries exceeded with url: /en/obra-carta/work-no-3209-amigos-2019-jardines-pereda/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1016)')))
Failed to fetch https://www.centrobotin.org/wp-content/uploads/2019/05/EXPO-CARTA-CREED-ENGLISH.pdf: HTTPSConnectionPool(host='www.centrobotin.org', port=443): Max retries exceeded with url: /wp-content/uploads/2019/05/EXPO-CARTA-CREED-ENGLISH.pdf (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1016)')))

 72%|███████▏  | 2114/2939 [27:14<41:42,  3.03s/it]

Failed to fetch https://www.charlotteobserver.com/living/religion/article137428913.html: HTTPSConnectionPool(host='www.charlotteobserver.com', port=443): Read timed out. (read timeout=10)

 72%|███████▏  | 2122/2939 [27:16<05:49,  2.34it/s]

Failed to fetch https://www.chessgames.com/perl/chess.pl?tid=98367: 403 Client Error: Forbidden for url: https://www.chessgames.com/perl/chess.pl?tid=98367
Failed to fetch https://www.chessgames.com/perl/chess.pl?tid=98367&kpage=45: 403 Client Error: Forbidden for url: https://www.chessgames.com/perl/chess.pl?tid=98367&kpage=45

 73%|███████▎  | 2136/2939 [27:31<05:38,  2.37it/s]

Failed to fetch https://www.coastergallery.com/1999/GA87.html: HTTPSConnectionPool(host='www.coastergallery.com', port=443): Max retries exceeded with url: /1999/GA87.html (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1016)')))

 73%|███████▎  | 2140/2939 [27:32<04:25,  3.01it/s]

Failed to fetch https://www.congress.gov/nomination/118th-congress/82: 403 Client Error: Forbidden for url: https://www.congress.gov/nomination/118th-congress/82
Failed to fetch https://www.congress.gov/nomination/98th-congress/907: 403 Client Error: Forbidden for url: https://www.congress.gov/nomination/98th-congress/907

 73%|███████▎  | 2146/2939 [27:36<09:20,  1.41it/s]

Failed to fetch https://www.coursehero.com/file/209878754/os-1docx/: 403 Client Error: Forbidden for url: https://www.coursehero.com/file/209878754/os-1docx/

 73%|███████▎  | 2157/2939 [27:50<10:36,  1.23it/s]

Failed to fetch https://www.dawn.com/news/1489714: 403 Client Error: Forbidden for url: https://www.dawn.com/news/1489714
Failed to fetch https://www.dawn.com/news/1701628: 403 Client Error: Forbidden for url: https://www.dawn.com/news/1701628

 73%|███████▎  | 2159/2939 [27:53<14:14,  1.10s/it]

Failed to fetch https://www.delahuntyfineart.com/artists/william-kentridge/: 502 Server Error: Bad Gateway or Proxy Error for url: https://www.delahuntyfineart.com/artists/william-kentridge/
Failed to fetch https://www.dell.com/community/en/conversations/virus-spyware/updates-111522-firefox-107/647fa0b9f4ccf8a8de5cac01: 403 Client Error: Forbidden for url: https://www.dell.com/community/en/conversations/virus-spyware/updates-111522-firefox-107/647fa0b9f4ccf8a8de5cac01

 74%|███████▍  | 2170/2939 [28:06<08:44,  1.47it/s]

Failed to fetch https://www.diomedia.com/stock-photo-fire-at-blenheim-palace---destruction-of-the-titian-gallery-image18080130.html: HTTPSConnectionPool(host='www.diomedia.com', port=443): Max retries exceeded with url: /stock-photo-fire-at-blenheim-palace---destruction-of-the-titian-gallery-image18080130.html (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1016)')))
Failed to fetch https://www.discogs.com/artist/108944-Immature: 403 Client Error: Forbidden for url: https://www.discogs.com/artist/108944-Immature
Failed to fetch https://www.discogs.com/artist/200161-Shai-3: 403 Client Error: Forbidden for url: https://www.discogs.com/artist/200161-Shai-3
Failed to fetch https://www.discogs.com/artist/453013-The-Mixers: 403 Client Error: Forbidden for url: https://www.discogs.com/artist/453013-The-Mixers

 74%|███████▍  | 2174/2939 [28:06<03:53,  3.27it/s]

Failed to fetch https://www.discogs.com/es/artist/2924383-Els-Aarne: 403 Client Error: Forbidden for url: https://www.discogs.com/es/artist/2924383-Els-Aarne
Failed to fetch https://www.discogs.com/release/13199258-Johnny-Rivers-Rewind: 403 Client Error: Forbidden for url: https://www.discogs.com/release/13199258-Johnny-Rivers-Rewind
Failed to fetch https://www.discogs.com/release/2287481-America-The-Last-Unicorn-Original-Soundtrack: 403 Client Error: Forbidden for url: https://www.discogs.com/release/2287481-America-The-Last-Unicorn-Original-Soundtrack
Failed to fetch https://www.discogs.com/release/2802201-Paul-Quinichette-Basie-Reunion: 403 Client Error: Forbidden for url: https://www.discogs.com/release/2802201-Paul-Quinichette-Basie-Reunion

 74%|███████▍  | 2176/2939 [28:06<02:51,  4.46it/s]

Failed to fetch https://www.discogs.com/release/2806294-Jerry-Lee-Lewis-She-Even-Woke-Me-Up-To-Say-Goodbye: 403 Client Error: Forbidden for url: https://www.discogs.com/release/2806294-Jerry-Lee-Lewis-She-Even-Woke-Me-Up-To-Say-Goodbye
Failed to fetch https://www.discogs.com/release/3509108-Avenger-Depraved-To-Black: 403 Client Error: Forbidden for url: https://www.discogs.com/release/3509108-Avenger-Depraved-To-Black
Failed to fetch https://www.discogs.com/release/6503660-Brenda-Memeza: 403 Client Error: Forbidden for url: https://www.discogs.com/release/6503660-Brenda-Memeza

 74%|███████▍  | 2182/2939 [29:03<1:25:47,  6.80s/it]

Failed to fetch https://www.dn.pt/arquivo/2004/interior/estacao-de-melecas-e-inaugurada-hoje-591035.html/: 404 Client Error: Not Found for url: https://www.dn.pt/arquivo/2004/interior/estacao-de-melecas-e-inaugurada-hoje-591035.html/

 74%|███████▍  | 2186/2939 [29:04<38:36,  3.08s/it]

Failed to fetch https://www.drugs.com/ingredient/barium-sulfate.html: 403 Client Error: Forbidden for url: https://www.drugs.com/ingredient/barium-sulfate.html

 74%|███████▍  | 2188/2939 [29:05<25:44,  2.06s/it]

Failed to fetch https://www.duo.uio.no/bitstream/handle/10852/50703/1/ingvaldsen_avhandling.pdf: 403 Client Error: Forbidden for url: https://www.duo.uio.no/bitstream/handle/10852/50703/1/ingvaldsen_avhandling.pdf

 75%|███████▍  | 2195/2939 [29:20<33:02,  2.67s/it]

Failed to fetch https://www.ebay.com/itm/125955908111: HTTPSConnectionPool(host='www.ebay.com', port=443): Read timed out. (read timeout=10)
Failed to fetch https://www.eclipsewise.com/lunar/LEdecade/LEdecade1981.html: 406 Client Error: Not Acceptable for url: https://www.eclipsewise.com/lunar/LEdecade/LEdecade1981.html

 75%|███████▍  | 2199/2939 [29:24<15:01,  1.22s/it]

Failed to fetch https://www.educatenepal.com/affiliation-body/detail/nepal-open-university: 406 Client Error: Not Acceptable for url: https://www.educatenepal.com/affiliation-body/detail/nepal-open-university
Failed to fetch https://www.eetindia.co.in/mindgrove-launches-indias-first-indigenously-designed-mcu-chip/: HTTPSConnectionPool(host='www.eetindia.co.in', port=443): Max retries exceeded with url: /mindgrove-launches-indias-first-indigenously-designed-mcu-chip/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f028bffe650>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
Failed to fetch https://www.efestivals.co.uk/festivals/arctangent/2013: 403 Client Error: Forbidden for url: https://www.efestivals.co.uk/festivals/arctangent/2013

 75%|███████▌  | 2209/2939 [29:27<03:23,  3.58it/s]

Failed to fetch https://www.emic.ee/?sisu=heliloojad&mid=58&id=128&lang=eng&action=view&method=biograafia: 403 Client Error: Forbidden for url: https://www.emic.ee/?sisu=heliloojad&mid=58&id=128&lang=eng&action=view&method=biograafia

 75%|███████▌  | 2217/2939 [29:28<02:17,  5.26it/s]

Failed to fetch https://www.eoas.info/biogs/P005870b.htm: 406 Client Error: Not Acceptable for url: https://www.eoas.info/biogs/P005870b.htm

 76%|███████▌  | 2226/2939 [29:31<02:51,  4.16it/s]

Failed to fetch https://www.espn.com/outdoors/bassmaster/about/news/story?page=bass_history: 404 Client Error: Not Found for url: https://www.espn.com/outdoors/bassmaster/about/news/story?page=bass_history

 76%|███████▌  | 2234/2939 [29:32<01:30,  7.83it/s]

Failed to fetch https://www.espncricinfo.com/cricketers/douglas-bennett-44186: 403 Client Error: Forbidden for url: https://www.espncricinfo.com/cricketers/douglas-bennett-44186
Failed to fetch https://www.espncricinfo.com/series/icc-world-twenty20-2012-13-531597/sri-lanka-vs-west-indies-final-533298/full-scorecard: 403 Client Error: Forbidden for url: https://www.espncricinfo.com/series/icc-world-twenty20-2012-13-531597/sri-lanka-vs-west-indies-final-533298/full-scorecard
Failed to fetch https://www.espncricinfo.com/series/ipl-2019-1165643/chennai-super-kings-vs-mumbai-indians-final-1181768/full-scorecard: 403 Client Error: Forbidden for url: https://www.espncricinfo.com/series/ipl-2019-1165643/chennai-super-kings-vs-mumbai-indians-final-1181768/full-scorecard
Failed to fetch https://www.espncricinfo.com/series/ipl-2019-1165643/kolkata-knight-riders-vs-sunrisers-hyderabad-2nd-match-1175357/full-scorecard: 403 Client Error: Forbidden for url: https://www.espncricinfo.com/series/ipl-2019-1165643/kolkata-knight-riders-vs-sunrisers-hyderabad-2nd-match-1175357/full-scorecard

 76%|███████▌  | 2236/2939 [29:32<01:20,  8.71it/s]

Failed to fetch https://www.espncricinfo.com/wisdenalmanack/content/story/228610.html: 403 Client Error: Forbidden for url: https://www.espncricinfo.com/wisdenalmanack/content/story/228610.html
Failed to fetch https://www.ethicawines.com/cantine/ricasoli/: 406 Client Error: Not Acceptable for url: https://www.ethicawines.com/cantine/ricasoli/

 76%|███████▋  | 2241/2939 [29:34<02:39,  4.38it/s]

Failed to fetch https://www.europeantour.com/dpworld-tour/scandinavian-masters-1992/results?round=4: 403 Client Error: Forbidden for url: https://www.europeantour.com/dpworld-tour/scandinavian-masters-1992/results?round=4

 77%|███████▋  | 2250/2939 [29:45<08:03,  1.42it/s]

Failed to fetch https://www.fai.org/gordonbennett-history: 403 Client Error: Forbidden for url: https://www.fai.org/gordonbennett-history

 77%|███████▋  | 2255/2939 [29:47<03:58,  2.87it/s]

Failed to fetch https://www.familysearch.org/en/blog/middle-east-art-music: 403 Client Error: Forbidden for url: https://www.familysearch.org/en/blog/middle-east-art-music
Failed to fetch https://www.famousfix.com/list/chairmen-of-the-estates-of-suriname: 403 Client Error: Forbidden for url: https://www.famousfix.com/list/chairmen-of-the-estates-of-suriname

 77%|███████▋  | 2256/2939 [29:47<04:08,  2.75it/s]

Failed to fetch https://www.farawear.ca/blog-2-1/blog-frequency-fabric: 404 Client Error: Not Found for url: https://www.farawear.ca/blog-2-1/blog-frequency-fabric

 77%|███████▋  | 2257/2939 [29:48<04:37,  2.46it/s]

Failed to fetch https://www.fc-suedtirol.com/it/news/vicenza-tanti-capitoli-nella-storia-del-calcio/24-774.html: HTTPSConnectionPool(host='www.fc-suedtirol.com', port=443): Max retries exceeded with url: /it/news/vicenza-tanti-capitoli-nella-storia-del-calcio/24-774.html (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1016)')))

 78%|███████▊  | 2279/2939 [29:59<05:59,  1.83it/s]

Failed to fetch https://www.fmsci.co.in/wp-content/uploads/2016/05/MECO-MOTORSPORTS-FMSCI-NRMKC-2017-POINTS-RD5.pdf: 404 Client Error: Not Found for url: https://www.fmsci.co.in/wp-content/uploads/2016/05/MECO-MOTORSPORTS-FMSCI-NRMKC-2017-POINTS-RD5.pdf

 78%|███████▊  | 2288/2939 [30:04<06:39,  1.63it/s]

Failed to fetch https://www.france24.com/en/20191023-tunisia-s-new-president-sworn-in-after-surprise-election-win: 403 Client Error: Forbidden for url: https://www.france24.com/en/20191023-tunisia-s-new-president-sworn-in-after-surprise-election-win
Failed to fetch https://www.frieze.com/article/lygia-pape: 403 Client Error: Forbidden for url: https://www.frieze.com/article/lygia-pape

 78%|███████▊  | 2292/2939 [30:12<20:38,  1.91s/it]

Failed to fetch https://www.funtimesmagazine.com/2020/12/16/339275/the-queen-of-african-pop-brenda-fassie: 404 Client Error: Not Found for url: https://funtimesmagazine.com/2020/12/16/339275/the-queen-of-african-pop-brenda-fassie

 78%|███████▊  | 2301/2939 [30:15<02:54,  3.66it/s]

Failed to fetch https://www.gbif.org/species/1404113: 403 Client Error: Forbidden for url: https://www.gbif.org/species/1404113
Failed to fetch https://www.gbif.org/species/165811206: 403 Client Error: Forbidden for url: https://www.gbif.org/species/165811206
Failed to fetch https://www.gbif.org/species/7003367: 403 Client Error: Forbidden for url: https://www.gbif.org/species/7003367

 79%|███████▉  | 2315/2939 [30:23<02:24,  4.31it/s]

Failed to fetch https://www.geochemsoc.org/honors/awards/vmgoldschmidtaward: 404 Client Error: Not Found for url: https://geochemsoc.org/honors/awards/vmgoldschmidtaward

 79%|███████▉  | 2317/2939 [30:23<02:40,  3.88it/s]

Failed to fetch https://www.getmusicbee.com/help/release-note/: 403 Client Error: Forbidden for url: https://www.getmusicbee.com/help/release-note/

 79%|███████▉  | 2323/2939 [30:26<05:18,  1.94it/s]

Failed to fetch https://www.ghanacelebrities.com/2020/08/01/today-in-history-exactly-58-years-ago-today-kwame-nkrumah-survives-a-deadly-bomb-attack-in-kulungugu/: 404 Client Error: Not Found for url: https://ghanacelebrities.com/2020/08/01/today-in-history-exactly-58-years-ago-today-kwame-nkrumah-survives-a-deadly-bomb-attack-in-kulungugu/

 80%|███████▉  | 2341/2939 [30:50<26:07,  2.62s/it]

Failed to fetch https://www.gov.za/news/media-programme-funeral-former-state-president-m-viljoen-10-jan-2007: HTTPSConnectionPool(host='www.gov.za', port=443): Max retries exceeded with url: /news/media-programme-funeral-former-state-president-m-viljoen-10-jan-2007 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f028bd10ed0>, 'Connection to www.gov.za timed out. (connect timeout=10)'))

 80%|███████▉  | 2342/2939 [31:00<44:56,  4.52s/it]

Failed to fetch https://www.gov.za/news/media-statements/presidency-announces-recipients-national-orders-10-nov-2021: HTTPSConnectionPool(host='www.gov.za', port=443): Read timed out. (read timeout=10)

 80%|███████▉  | 2343/2939 [31:11<1:02:23,  6.28s/it]

Failed to fetch https://www.gov.za/news/p-mlambo-ngcuka-attend-funeral-former-state-president-m-viljoen-13-jan-06-jan-2007: HTTPSConnectionPool(host='www.gov.za', port=443): Read timed out. (read timeout=10)

 81%|████████  | 2368/2939 [32:06<07:13,  1.32it/s]

Failed to fetch https://www.helis.com/database/unit/2073-TCG-Yavuz: 403 Client Error: Forbidden for url: https://www.helis.com/database/unit/2073-TCG-Yavuz

 81%|████████  | 2371/2939 [32:07<03:46,  2.51it/s]

Failed to fetch https://www.hellenicaworld.com/Art/Paintings/en/WillHicokLow.html: HTTPSConnectionPool(host='www.hellenicaworld.com', port=443): Max retries exceeded with url: /Art/Paintings/en/WillHicokLow.html (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1016)')))

 81%|████████  | 2374/2939 [32:08<03:53,  2.42it/s]

Failed to fetch https://www.heritageohio.org/cleveland-hanna-theatre/: 404 Client Error: Not Found for url: https://heritageohio.org/cleveland-hanna-theatre/

 81%|████████  | 2381/2939 [32:11<02:37,  3.55it/s]

Failed to fetch https://www.history.navy.mil/browse-by-topic/people/chiefs-of-naval-operations/admiral-william-h--standley.html: HTTPSConnectionPool(host='www.history.navy.mil', port=443): Max retries exceeded with url: /browse-by-topic/people/chiefs-of-naval-operations/admiral-william-h--standley.html (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1016)')))

 81%|████████  | 2382/2939 [32:12<05:31,  1.68it/s]

Failed to fetch https://www.hmdb.org/m.asp?m=146932: 403 Client Error: Forbidden for url: https://www.hmdb.org/m.asp?m=146932

 81%|████████▏ | 2391/2939 [32:18<07:02,  1.30it/s]

Failed to fetch https://www.hydecollection.org/blog/2016/norman-rockwell-1960s-thursday-jan-7-2016/: 404 Client Error: Not Found for url: https://www.hydecollection.org/blog/2016/norman-rockwell-1960s-thursday-jan-7-2016/

 82%|████████▏ | 2397/2939 [32:39<14:25,  1.60s/it]

Failed to fetch https://www.ifkcs.org/historik/historik.php: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

 82%|████████▏ | 2406/2939 [32:46<06:44,  1.32it/s]

Failed to fetch https://www.independent.co.uk/news/world/africa/surgeon-jailed-over-death-of-first-lady-1791712.html): Exceeded 30 redirects.

 82%|████████▏ | 2407/2939 [32:47<05:20,  1.66it/s]

Failed to fetch https://www.india9.com/i9show/-Jammu-and-Kashmir/Dudhganga-River-45673.htm: HTTPSConnectionPool(host='www.india9.com', port=443): Max retries exceeded with url: /i9show/-Jammu-and-Kashmir/Dudhganga-River-45673.htm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f028b1ee910>: Failed to establish a new connection: [Errno 111] Connection refused'))

 82%|████████▏ | 2410/2939 [32:50<06:26,  1.37it/s]

Failed to fetch https://www.indiaspeakersbureau.in/speakers/sonam-wangchuk/: 406 Client Error: Not Acceptable for url: https://www.indiaspeakersbureau.in/speakers/sonam-wangchuk/

 82%|████████▏ | 2413/2939 [32:50<03:08,  2.79it/s]

Failed to fetch https://www.infosecinstitute.com/resources/threat-intelligence/vault-7-leaks-inside-cia-secret-kingdom-july-august-07/: 403 Client Error: Forbidden for url: https://www.infosecinstitute.com/resources/threat-intelligence/vault-7-leaks-inside-cia-secret-kingdom-july-august-07/

 82%|████████▏ | 2417/2939 [32:51<02:41,  3.24it/s]

Failed to fetch https://www.insidethegames.biz/articles/1114757/usmanov-to-be-reelected-fencing: 403 Client Error: Forbidden for url: https://www.insidethegames.biz/articles/1114757/usmanov-to-be-reelected-fencing
Failed to fetch https://www.intel.com/content/www/us/en/products/sku/195306/intel-core-i79700e-processor-12m-cache-up-to-4-40-ghz/specifications.html: 403 Client Error: Forbidden for url: https://www.intel.com/content/www/us/en/products/sku/195306/intel-core-i79700e-processor-12m-cache-up-to-4-40-ghz/specifications.html

 82%|████████▏ | 2418/2939 [32:53<05:13,  1.66it/s]

Failed to fetch https://www.internationalmathematicsmaster.org/archive/marcelo-viana: 404 Client Error: Not Found for url: https://internationalmathematicsmaster.org/archive/marcelo-viana

 82%|████████▏ | 2419/2939 [32:57<12:26,  1.44s/it]

Failed to fetch https://www.internationalnewsandviews.com/himachal-pradesh-is-known-as-veer-bhoomi/: 404 Client Error: Not Found for url: https://internationalnewsandviews.com/himachal-pradesh-is-known-as-veer-bhoomi/
Failed to fetch https://www.invaluable.com/auction-lot/will-hicok-low-ny-french-1853-1932-oil-painting-a-293-c-1374c919de: 403 Client Error: Forbidden for url: https://www.invaluable.com/auction-lot/will-hicok-low-ny-french-1853-1932-oil-painting-a-293-c-1374c919de

 83%|████████▎ | 2426/2939 [33:01<06:03,  1.41it/s]

Failed to fetch https://www.iscb.org/iscb-awards/1129: 404 Client Error: Not Found for url: https://www.iscb.org/iscb-awards/1129

 83%|████████▎ | 2427/2939 [33:01<05:08,  1.66it/s]

Failed to fetch https://www.iscb.org/iscb-awards/accomplishment-senior-scientist-award: 404 Client Error: Not Found for url: https://www.iscb.org/iscb-awards/accomplishment-senior-scientist-award

 83%|████████▎ | 2430/2939 [33:02<03:17,  2.58it/s]

Failed to fetch https://www.iucnredlist.org/species/6066/12381943: 403 Client Error: Forbidden for url: https://www.iucnredlist.org/species/6066/12381943

 83%|████████▎ | 2437/2939 [33:04<02:33,  3.28it/s]

Failed to fetch https://www.jambase.com/festival/cape-town-international-jazz-festival-2019: 403 Client Error: Forbidden for url: https://www.jambase.com/festival/cape-town-international-jazz-festival-2019

 83%|████████▎ | 2440/2939 [33:05<01:33,  5.36it/s]

Failed to fetch https://www.jatland.com/home/Bandipora: 403 Client Error: Forbidden for url: https://www.jatland.com/home/Bandipora
Failed to fetch https://www.javatpoint.com/louis-armstrong: HTTPSConnectionPool(host='www.javatpoint.com', port=443): Max retries exceeded with url: /louis-armstrong (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f028be7eed0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
Failed to fetch https://www.javatpoint.com/ms-subbulakshmi: HTTPSConnectionPool(host='www.javatpoint.com', port=443): Max retries exceeded with url: /ms-subbulakshmi (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0287a716d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

 83%|████████▎ | 2447/2939 [33:09<02:37,  3.13it/s]

Failed to fetch https://www.jstor.org/stable/25608025?seq=2: 403 Client Error: Forbidden for url: https://www.jstor.org/stable/25608025?seq=2
Failed to fetch https://www.jstor.org/stable/3597187: 403 Client Error: Forbidden for url: https://www.jstor.org/stable/3597187
Failed to fetch https://www.jstor.org/stable/40732660: 403 Client Error: Forbidden for url: https://www.jstor.org/stable/40732660

 83%|████████▎ | 2452/2939 [33:15<11:03,  1.36s/it]

Failed to fetch https://www.kashmirhills.com/hotels/gulmarg/ferozepur-nallah-in-gulmarg/: 406 Client Error: Not Acceptable for url: https://www.kashmirhills.com/hotels/gulmarg/ferozepur-nallah-in-gulmarg/

 84%|████████▎ | 2457/2939 [33:27<27:54,  3.47s/it]

Failed to fetch https://www.kgw.com/article/entertainment/television/programs/straight-talk/straight-talk-portland-oregon-mingus-mapps-city-council/283-c294f104-d0fb-4ab2-a2f8-3503b849366f: HTTPSConnectionPool(host='www.kgw.com', port=443): Read timed out. (read timeout=10)

 84%|████████▍ | 2473/2939 [33:41<03:20,  2.32it/s]

Failed to fetch https://www.learnedsociety.wales/fellow/mari-lloyd-williams-2/: 404 Client Error: Not Found for url: https://www.learnedsociety.wales/fellow/mari-lloyd-williams-2/

 84%|████████▍ | 2477/2939 [33:49<08:29,  1.10s/it]

Failed to fetch https://www.liberation.fr/societe/1998/02/28/nathalie-menigon-epouse-jean-marc-rouillan_228486/: 403 Client Error: Forbidden for url: https://www.liberation.fr/societe/1998/02/28/nathalie-menigon-epouse-jean-marc-rouillan_228486/

 84%|████████▍ | 2482/2939 [33:51<03:16,  2.32it/s]

Failed to fetch https://www.liherald.com/stories/marge-suozzi-dies-at-93-after-a-life-of-giving: 403 Client Error: 403 for url: https://www.liherald.com/stories/marge-suozzi-dies-at-93-after-a-life-of-giving

 85%|████████▍ | 2493/2939 [34:04<13:02,  1.75s/it]

Failed to fetch https://www.longmarchtofreedom.co.za/BronzeStatues/Artist/618a93ff4ded043532a567d3: 404 Client Error: Not Found for url: https://longmarchtofreedom.co.za/BronzeStatues/Artist/618a93ff4ded043532a567d3
Failed to fetch https://www.lookandlearn.com/history-images/YM0343588/Farnese-Hercules?t=4&n=554226: 403 Client Error: Forbidden for url: https://www.lookandlearn.com/history-images/YM0343588/Farnese-Hercules?t=4&n=554226

 85%|████████▌ | 2503/2939 [34:11<04:58,  1.46it/s]

Failed to fetch https://www.lyricsnepal.com/product/voice-king-narayan-gopal/: 429 Client Error: Too Many Requests for url: https://www.lyricsnepal.com/product/voice-king-narayan-gopal/

 85%|████████▌ | 2504/2939 [34:13<05:51,  1.24it/s]

Failed to fetch https://www.mantissaart.com/product-details1.aspx?&catid=10177: HTTPSConnectionPool(host='www.mantissaart.com', port=443): Max retries exceeded with url: /product-details1.aspx?&catid=10177 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0289845f50>: Failed to establish a new connection: [Errno -2] Name or service not known'))

 85%|████████▌ | 2508/2939 [34:14<04:06,  1.75it/s]

Failed to fetch https://www.marinespecies.org/aphia.php?id=414748&p=taxdetails: 403 Client Error: Forbidden for url: https://www.marinespecies.org/aphia.php?id=414748&p=taxdetails

 86%|████████▌ | 2515/2939 [34:17<02:26,  2.90it/s]

Failed to fetch https://www.mdpi.com/2078-2489/12/5/187: 403 Client Error: Forbidden for url: https://www.mdpi.com/2078-2489/12/5/187

 86%|████████▌ | 2521/2939 [34:20<02:54,  2.40it/s]

Failed to fetch https://www.metal-archives.com/reviews/Avenger/Depraved_to_Black/4926/: 403 Client Error: Forbidden for url: https://www.metal-archives.com/reviews/Avenger/Depraved_to_Black/4926/
Failed to fetch https://www.metmuseum.org/art/collection/search/343588: HTTPSConnectionPool(host='www.metmuseum.org', port=443): Max retries exceeded with url: /art/collection/search/343588 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0283a17310>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
Failed to fetch https://www.metmuseum.org/research-centers/leonard-a-lauder-research-center/research-resources/modern-art-index-project/cone: HTTPSConnectionPool(host='www.metmuseum.org', port=443): Max retries exceeded with url: /research-centers/leonard-a-lauder-research-center/research-resources/modern-art-index-project/cone (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0283a17dd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

 86%|████████▌ | 2526/2939 [34:21<01:24,  4.87it/s]

Failed to fetch https://www.microsoft.com/en-us/sql-server/blog/2009/03/20/microsoft-colleagues-win-acm-award/: 403 Client Error: Forbidden for url: https://www.microsoft.com/en-us/sql-server/blog/2009/03/20/microsoft-colleagues-win-acm-award/

 86%|████████▌ | 2531/2939 [34:23<02:41,  2.52it/s]

Failed to fetch https://www.middletemple.org.uk/bencher-persons-view?cid=31807: 404 Client Error: Not Found for url: https://www.middletemple.org.uk/bencher-persons-view?cid=31807
Failed to fetch https://www.mobygames.com/game/348/tomb-raider/trivia/: 403 Client Error: Forbidden for url: https://www.mobygames.com/game/348/tomb-raider/trivia/

 86%|████████▌ | 2533/2939 [34:23<01:49,  3.70it/s]

Failed to fetch https://www.modernghana.com/news/787795/the-journey-of-presidential-elections-in-ghana-from-1992-to.html: 403 Client Error: Forbidden for url: https://www.modernghana.com/news/787795/the-journey-of-presidential-elections-in-ghana-from-1992-to.html
Failed to fetch https://www.moma.org/audio/playlist/243/3119: 403 Client Error: Forbidden for url: https://www.moma.org/audio/playlist/243/3119

 86%|████████▋ | 2538/2939 [37:44<2:19:15, 20.84s/it]

Failed to fetch https://www.moma.org/explore/inside_out/2009/12/03/a-close-look-frida-kahlo-s-fulang-chang-and-i/: 403 Client Error: Forbidden for url: https://www.moma.org/explore/inside_out/2009/12/03/a-close-look-frida-kahlo-s-fulang-chang-and-i/
Failed to fetch https://www.monash.vic.gov.au/About-Us/News/Monash-Gallery-of-Art-rebrands-as-MAPh-Museum-of-Australian-Photography: 403 Client Error: Forbidden for url: https://www.monash.vic.gov.au/About-Us/News/Monash-Gallery-of-Art-rebrands-as-MAPh-Museum-of-Australian-Photography

 86%|████████▋ | 2540/2939 [37:45<1:26:18, 12.98s/it]

Failed to fetch https://www.motorbikecatalog.com/make/honda/cl125/cl125/1969.html: 403 Client Error: Forbidden for url: https://www.motorbikecatalog.com/make/honda/cl125/cl125/1969.html

 87%|████████▋ | 2548/2939 [37:47<10:29,  1.61s/it]

Failed to fetch https://www.museumsofimpact.eu/en/news/new-tool-moi-framework-helps-museum-increase-their-social-impact: HTTPSConnectionPool(host='www.museumsofimpact.eu', port=443): Max retries exceeded with url: /en/news/new-tool-moi-framework-helps-museum-increase-their-social-impact (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0286282250>: Failed to establish a new connection: [Errno -2] Name or service not known'))
Failed to fetch https://www.musicgateway.com/song-lyrics/mariah-carey/hero: 403 Client Error: Forbidden for url: https://www.musicgateway.com/song-lyrics/mariah-carey/hero

 87%|████████▋ | 2551/2939 [37:48<05:30,  1.17it/s]

Failed to fetch https://www.mutualart.com/Artist/Robert-Walls/F1175F9016037D5D: 595 Server Error:  for url: https://www.mutualart.com/Artist/Robert-Walls/F1175F9016037D5D

 87%|████████▋ | 2554/2939 [37:49<04:08,  1.55it/s]

Failed to fetch https://www.mykhel.com/cricket/ipl-2015-scorecard-s9978-818660/: 403 Client Error: Forbidden for url: https://www.mykhel.com/cricket/ipl-2015-scorecard-s9978-818660/

 87%|████████▋ | 2559/2939 [37:50<01:45,  3.59it/s]

Failed to fetch https://www.nascar.com/gallery/jimmie-johnson-through-the-years/: 403 Client Error: Forbidden for url: https://www.nascar.com/gallery/jimmie-johnson-through-the-years/

 87%|████████▋ | 2563/2939 [37:52<02:12,  2.85it/s]

Failed to fetch https://www.national-football-teams.com/player/41778/Frank_Sanny_Jacobsson.html: 500 Server Error: Internal Server Error for url: https://www.national-football-teams.com/player/41778/Frank_Sanny_Jacobsson.html

 87%|████████▋ | 2564/2939 [37:52<02:08,  2.92it/s]

Failed to fetch https://www.national-football-teams.com/player/62612/Edward_Morris.html: 500 Server Error: Internal Server Error for url: https://www.national-football-teams.com/player/62612/Edward_Morris.html

 87%|████████▋ | 2569/2939 [37:58<06:12,  1.01s/it]

Failed to fetch https://www.nationsonline.org/oneworld/map/nigeria-political-map.htm: 403 Client Error: Forbidden for url: https://www.nationsonline.org/oneworld/map/nigeria-political-map.htm

 88%|████████▊ | 2580/2939 [38:12<09:47,  1.64s/it]

Failed to fetch https://www.ncronline.org/news/harry-belafonte-entertainer-and-activist-dead-96: 403 Client Error: Forbidden for url: https://www.ncronline.org/news/harry-belafonte-entertainer-and-activist-dead-96
Failed to fetch https://www.ndtv.com/india-news/omar-abdullahs-sister-challenges-his-detention-in-supreme-court-after-hes-charged-under-stringent-pu-2177695: 403 Client Error: Forbidden for url: https://www.ndtv.com/india-news/omar-abdullahs-sister-challenges-his-detention-in-supreme-court-after-hes-charged-under-stringent-pu-2177695

 88%|████████▊ | 2596/2939 [38:19<01:48,  3.15it/s]

Failed to fetch https://www.np.emb-japan.go.jp/100th/pio1.html: 403 Client Error: Forbidden for url: https://www.np.emb-japan.go.jp/100th/pio1.html
Failed to fetch https://www.npg.org.uk/collections/research/programmes/early-history-of-mezzotint/john-smith-mezzotint-printmaker-biography.php: 403 Client Error: Forbidden for url: https://www.npg.org.uk/collections/research/programmes/early-history-of-mezzotint/john-smith-mezzotint-printmaker-biography.php
Failed to fetch https://www.npg.org.uk/collections/search/portraitExtended/mw06269/Ellen-Terry-Choosing: 403 Client Error: Forbidden for url: https://www.npg.org.uk/collections/search/portraitExtended/mw06269/Ellen-Terry-Choosing

 89%|████████▉ | 2613/2939 [38:34<15:03,  2.77s/it]

Failed to fetch https://www.oneindia.com/2007/03/10/eighteenth-ignou-convocation-on-march-17-1174142985.html: 403 Client Error: Forbidden for url: https://www.oneindia.com/2007/03/10/eighteenth-ignou-convocation-on-march-17-1174142985.html
Failed to fetch https://www.oneindia.com/list-of-chief-ministers-of-karnataka/: 403 Client Error: Forbidden for url: https://www.oneindia.com/list-of-chief-ministers-of-karnataka/

 89%|████████▉ | 2616/2939 [38:34<06:58,  1.30s/it]

Failed to fetch https://www.onesmedia.com/music-c-10_65/american-album-of-familiar-music-p-958.html: 406 Client Error: Not Acceptable for url: https://www.onesmedia.com/music-c-10_65/american-album-of-familiar-music-p-958.html

 89%|████████▉ | 2625/2939 [38:42<05:03,  1.03it/s]

Failed to fetch https://www.paleo.pan.pl/pracownicy/kielan-jaworowska/zofia_kielan-jaworowska.html: 404 Client Error: Not Found for url: https://www.paleo.pan.pl/pracownicy/kielan-jaworowska/zofia_kielan-jaworowska.html

 89%|████████▉ | 2627/2939 [38:43<03:59,  1.30it/s]

Failed to fetch https://www.palestinepnc.org/en/council-establishment: 404 Client Error: Not Found for url: https://www.palestinepnc.org/en/council-establishment

 90%|████████▉ | 2631/2939 [38:43<01:27,  3.52it/s]

Failed to fetch https://www.patheos.com/blogs/danpeterson/2024/02/103967.html: 403 Client Error: Forbidden for url: https://www.patheos.com/blogs/danpeterson/2024/02/103967.html
Failed to fetch https://www.patheos.com/faith-figures-database/s/steven-furtick: 403 Client Error: Forbidden for url: https://www.patheos.com/faith-figures-database/s/steven-furtick

 90%|████████▉ | 2632/2939 [38:44<01:19,  3.87it/s]

Failed to fetch https://www.patrimoine-culturel.gouv.qc.ca/rpcq/detail.do?id=110371&methode=consulter&type=bien: HTTPSConnectionPool(host='www.patrimoine-culturel.mcc.gouv.qc.ca', port=443): Max retries exceeded with url: /maintenance (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f028bdf23d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
Failed to fetch https://www.patrimoine-culturel.gouv.qc.ca/rpcq/detail.do?methode=consulter&id=172110&type=bien: HTTPSConnectionPool(host='www.patrimoine-culturel.mcc.gouv.qc.ca', port=443): Max retries exceeded with url: /maintenance (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f03105d3850>: Failed to establish a new connection: [Errno -2] Name or service not known'))

 90%|████████▉ | 2639/2939 [39:00<11:07,  2.23s/it]

Failed to fetch https://www.phocuswrightconference.com/Whos-Coming/Speakers/2023/Dangui-Oduber: 405 Client Error: Not Allowed for url: https://www.phocuswrightconference.com/Whos-Coming/Speakers/2023/Dangui-Oduber

 90%|████████▉ | 2643/2939 [39:12<18:37,  3.78s/it]

Failed to fetch https://www.pikaialodge.com/awards.php: HTTPSConnectionPool(host='www.pikaialodge.com', port=443): Read timed out. (read timeout=10)

 90%|█████████ | 2648/2939 [39:14<04:19,  1.12it/s]

Failed to fetch https://www.playmakerstats.com/player/edward-morris/244633: 403 Client Error: Forbidden for url: https://www.playmakerstats.com/player/edward-morris/244633
Failed to fetch https://www.playmakerstats.com/player/noel-turner/111102: 403 Client Error: Forbidden for url: https://www.playmakerstats.com/player/noel-turner/111102
Failed to fetch https://www.politico.com/story/2007/02/this-day-on-capitol-hill-february-23-002845: 403 Client Error: Forbidden for url: https://www.politico.com/story/2007/02/this-day-on-capitol-hill-february-23-002845

 90%|█████████ | 2651/2939 [39:25<13:32,  2.82s/it]

Failed to fetch https://www.presidentiallibrary.go.ke/he-daniel-arap-moi: HTTPSConnectionPool(host='www.presidentiallibrary.go.ke', port=443): Max retries exceeded with url: /he-daniel-arap-moi (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f028a347c90>, 'Connection to www.presidentiallibrary.go.ke timed out. (connect timeout=10)'))

 90%|█████████ | 2653/2939 [39:26<08:20,  1.75s/it]

Failed to fetch https://www.prints-online.com/hans-bohn-19921200.html: 403 Client Error: Forbidden for url: https://www.prints-online.com/hans-bohn-19921200.html

 91%|█████████ | 2660/2939 [39:31<03:21,  1.38it/s]

Failed to fetch https://www.pulselive.co.ke/news/counties-amason-jeffah-kingi-profile/d1zjt9z: 404 Client Error: Not Found for url: https://www.pulse.co.ke/news/counties-amason-jeffah-kingi-profile/d1zjt9z

 91%|█████████ | 2661/2939 [39:31<02:38,  1.76it/s]

Failed to fetch https://www.racingpost.com/profile/horse/892540/donjuan-triumphant/fee-history: 406 Client Error: Not Acceptable for url: https://www.racingpost.com/profile/horse/892540/donjuan-triumphant/fee-history

 91%|█████████ | 2669/2939 [39:36<01:29,  3.02it/s]

Failed to fetch https://www.reddit.com/r/Damnthatsinteresting/comments/18tm1sg/a_japanese_burglar_was_unmasked_as_a_74yearold/?rdt=34201: 403 Client Error: Blocked for url: https://www.reddit.com/r/Damnthatsinteresting/comments/18tm1sg/a_japanese_burglar_was_unmasked_as_a_74yearold/?rdt=34201
Failed to fetch https://www.reddit.com/r/WeirdWings/comments/17udb9p/the_first_of_two_cierva_w11_air_horse_triple/: 403 Client Error: Blocked for url: https://www.reddit.com/r/WeirdWings/comments/17udb9p/the_first_of_two_cierva_w11_air_horse_triple/
Failed to fetch https://www.reddit.com/r/boardgames/comments/10e52d/heroquest_whats_in_a_fullcomplete_box/: 403 Client Error: Blocked for url: https://www.reddit.com/r/boardgames/comments/10e52d/heroquest_whats_in_a_fullcomplete_box/
Failed to fetch https://www.reddit.com/r/firefox/comments/mu0iy7/firefox_880_see_all_new_features_updates_and_fixes/: 403 Client Error: Blocked for url: https://www.reddit.com/r/firefox/comments/mu0iy7/firefox_880_see_all_new_features_updates_and_fixes/

 91%|█████████ | 2671/2939 [39:37<01:53,  2.36it/s]

Failed to fetch https://www.reedsmith.com/en/perspectives/2020/06/the-adoption-of-the-chinese-civil-code-and-its-implications-on-contracts: 404 Client Error: Not Found for url: https://www.reedsmith.com/en/perspectives/2020/06/the-adoption-of-the-chinese-civil-code-and-its-implications-on-contracts

 91%|█████████ | 2675/2939 [39:39<01:45,  2.50it/s]

Failed to fetch https://www.researchgate.net/post/What_are_the_most_prominent_evidences_of_Paleolithic_period_And_what_are_the_most_prominent_features_of_Neolithic_period: 403 Client Error: Forbidden for url: https://www.researchgate.net/post/What_are_the_most_prominent_evidences_of_Paleolithic_period_And_what_are_the_most_prominent_features_of_Neolithic_period
Failed to fetch https://www.researchgate.net/profile/Inigo-Sanchez-3/publication/258872655_Making_the_lynx/links/0c9605294cc2dc7e45000000/Making-the-lynx.pdf: 403 Client Error: Forbidden for url: https://www.researchgate.net/profile/Inigo-Sanchez-3/publication/258872655_Making_the_lynx/links/0c9605294cc2dc7e45000000/Making-the-lynx.pdf
Failed to fetch https://www.researchgate.net/publication/241680512_The_life_and_work_of_Kuo-Tsai_Chen: 403 Client Error: Forbidden for url: https://www.researchgate.net/publication/241680512_The_life_and_work_of_Kuo-Tsai_Chen

 91%|█████████ | 2679/2939 [39:39<00:54,  4.78it/s]

Failed to fetch https://www.researchgate.net/publication/276064647_OARSI_Clinical_Trials_Recommendations_Soluble_biomarker_assessments_in_clinical_trials_in_osteoarthritis: 403 Client Error: Forbidden for url: https://www.researchgate.net/publication/276064647_OARSI_Clinical_Trials_Recommendations_Soluble_biomarker_assessments_in_clinical_trials_in_osteoarthritis
Failed to fetch https://www.researchgate.net/publication/289248977_Detecting_Driver_Mental_Fatigue_Based_on_EEG_Alpha_Power_Changes_during_Simulated_Driving: 403 Client Error: Forbidden for url: https://www.researchgate.net/publication/289248977_Detecting_Driver_Mental_Fatigue_Based_on_EEG_Alpha_Power_Changes_during_Simulated_Driving
Failed to fetch https://www.researchgate.net/publication/304460742_Identifying_semantic_role_clusters_and_alignment_types_via_microrole_coexpression_tendencies: 403 Client Error: Forbidden for url: https://www.researchgate.net/publication/304460742_Identifying_semantic_role_clusters_and_alignment_types_via_microrole_coexpression_tendencies
Failed to fetch https://www.researchgate.net/publication/319901238_Aluminium_Metal_Matrix_Composites_-_A_Review': 403 Client Error: Forbidden for url: https://www.researchgate.net/publication/319901238_Aluminium_Metal_Matrix_Composites_-_A_Review'

 91%|█████████▏| 2683/2939 [39:39<00:34,  7.45it/s]

Failed to fetch https://www.researchgate.net/publication/346394373_Voter_Turnouts_in_Presidential_Elections_in_Ghana_A_Political_Economy_Analysis_Using_District-Level_Data: 403 Client Error: Forbidden for url: https://www.researchgate.net/publication/346394373_Voter_Turnouts_in_Presidential_Elections_in_Ghana_A_Political_Economy_Analysis_Using_District-Level_Data
Failed to fetch https://www.researchgate.net/publication/349291260_EEG-Based_Driving_Fatigue_Detection_Using_a_Two-Level_Learning_Hierarchy_Radial_Basis_Function: 403 Client Error: Forbidden for url: https://www.researchgate.net/publication/349291260_EEG-Based_Driving_Fatigue_Detection_Using_a_Two-Level_Learning_Hierarchy_Radial_Basis_Function
Failed to fetch https://www.researchgate.net/publication/351143684_Classification_of_Relaxation_and_Concentration_Mental_States_with_EEG: 403 Client Error: Forbidden for url: https://www.researchgate.net/publication/351143684_Classification_of_Relaxation_and_Concentration_Mental_States_with_EEG
Failed to fetch https://www.researchgate.net/publication/352524665_Latin_America_in_UNESCO_Science_Report_2021: 403 Client Error: Forbidden for url: https://www.researchgate.net/publication/352524665_Latin_America_in_UNESCO_Science_Report_2021

 92%|█████████▏| 2691/2939 [39:42<01:18,  3.17it/s]

Failed to fetch https://www.roedl.com/insights/china-civil-code: 404 Client Error: Not Found for url: https://www.roedl.com/insights/china-civil-code
Failed to fetch https://www.rogerebert.com/interviews/rosie-perez-on-a-roll: 403 Client Error: Forbidden for url: https://www.rogerebert.com/interviews/rosie-perez-on-a-roll

 92%|█████████▏| 2707/2939 [40:00<03:43,  1.04it/s]

Failed to fetch https://www.saturdayeveningpost.com/2011/05/rockwell-changed-illustration/: 404 Client Error: Not Found for url: https://www.saturdayeveningpost.com/2011/05/rockwell-changed-illustration/

 92%|█████████▏| 2710/2939 [40:04<04:34,  1.20s/it]

Failed to fetch https://www.scholarsatrisk.org/actions/niloufar-bayani-iran/: 404 Client Error: Not Found for url: https://www.scholarsatrisk.org/actions/niloufar-bayani-iran/

 92%|█████████▏| 2714/2939 [40:09<03:22,  1.11it/s]

Failed to fetch https://www.sciencedirect.com/science/article/abs/pii/S0016003203000462: 403 Client Error: Forbidden for url: https://www.sciencedirect.com/science/article/abs/pii/S0016003203000462
Failed to fetch https://www.sciencedirect.com/science/article/pii/S095461110600401X: 403 Client Error: Forbidden for url: https://www.sciencedirect.com/science/article/pii/S095461110600401X

 92%|█████████▏| 2715/2939 [40:09<02:33,  1.46it/s]

Failed to fetch https://www.sciencedirect.com/topics/social-sciences/sharia-law: 403 Client Error: Forbidden for url: https://www.sciencedirect.com/topics/social-sciences/sharia-law

 93%|█████████▎| 2724/2939 [40:15<01:36,  2.23it/s]

Failed to fetch https://www.scotsconnection.com/clan_crests/agnew.htm: 403 Client Error: Forbidden for url: https://www.scotsconnection.com/clan_crests/agnew.htm
Failed to fetch https://www.scotsconnection.com/clan_crests/boyd.htm: 403 Client Error: Forbidden for url: https://www.scotsconnection.com/clan_crests/boyd.htm

 93%|█████████▎| 2731/2939 [40:21<01:32,  2.24it/s]

Failed to fetch https://www.shipspotting.com/photos/1354303: 403 Client Error: Forbidden for url: https://www.shipspotting.com/photos/1354303

 93%|█████████▎| 2735/2939 [40:22<01:06,  3.08it/s]

Failed to fetch https://www.showstudio.com/contributors/junya_watanabe: 403 Client Error: Forbidden for url: https://www.showstudio.com/contributors/junya_watanabe

 93%|█████████▎| 2746/2939 [40:27<01:49,  1.77it/s]

Failed to fetch https://www.sport-olympic.gr/sp/index.php/olympic-games/modern-olympic-games/summer-olympic-games/1932-los-angeles-summer-olympics/1649-1932-summer-olympics-the-results-art-competitions: HTTPSConnectionPool(host='www.sport-olympic.gr', port=443): Max retries exceeded with url: /sp/index.php/olympic-games/modern-olympic-games/summer-olympic-games/1932-los-angeles-summer-olympics/1649-1932-summer-olympics-the-results-art-competitions (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0288aa7ed0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
Failed to fetch https://www.sport-olympic.gr/sp/index.php/olympic-games/modern-olympic-games/summer-olympic-games/1964-tokyo-summer-olympics/18421-1964-summer-olympics-the-results-fencing-women: HTTPSConnectionPool(host='www.sport-olympic.gr', port=443): Max retries exceeded with url: /sp/index.php/olympic-games/modern-olympic-games/summer-olympic-games/1964-tokyo-summer-olympics/18421-1964-summer-olympics-the-results-fencing-women (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f02856dec90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

 94%|█████████▎| 2753/2939 [40:30<01:18,  2.38it/s]

Failed to fetch https://www.ssense.com/en-us/editorial/fashion/decoding-jun-takahashis-undercover: 403 Client Error: Forbidden for url: https://www.ssense.com/en-us/editorial/fashion/decoding-jun-takahashis-undercover
Failed to fetch https://www.ssense.com/en-us/editorial/fashion/total-exposure-with-mowalola-ogunlesi: 403 Client Error: Forbidden for url: https://www.ssense.com/en-us/editorial/fashion/total-exposure-with-mowalola-ogunlesi
Failed to fetch https://www.stadion.fi/en/info/stadium-info/olympic-stadium: HTTPSConnectionPool(host='www.stadion.fi', port=443): Max retries exceeded with url: /en/info/stadium-info/olympic-stadium (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f028091a4d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

 94%|█████████▍| 2760/2939 [40:38<02:58,  1.00it/s]

Failed to fetch https://www.stefanparkman.com/biography/: 403 Client Error: Forbidden for url: https://www.stefanparkman.com/biography/

 94%|█████████▍| 2765/2939 [40:49<08:57,  3.09s/it]

Failed to fetch https://www.superxv.com/waratahs-work-hard-for-victory-over-lions/: HTTPSConnectionPool(host='www.superxv.com', port=443): Max retries exceeded with url: /waratahs-work-hard-for-victory-over-lions/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f0310acc990>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

 94%|█████████▍| 2769/2939 [40:51<03:06,  1.10s/it]

Failed to fetch https://www.telegraph.co.uk/education/3078764/Town-vs-Gown-Cheltenham-Gloucestershire.html: 403 Client Error: Forbidden for url: https://www.telegraph.co.uk/education/3078764/Town-vs-Gown-Cheltenham-Gloucestershire.html

 95%|█████████▍| 2780/2939 [41:00<01:06,  2.39it/s]

Failed to fetch https://www.thecanadianencyclopedia.ca/en/article/alain-stanke: 403 Client Error: Forbidden for url: https://www.thecanadianencyclopedia.ca/en/article/alain-stanke
Failed to fetch https://www.thecanadianencyclopedia.ca/en/article/emma-albani-emc: 403 Client Error: Forbidden for url: https://www.thecanadianencyclopedia.ca/en/article/emma-albani-emc

 95%|█████████▍| 2782/2939 [41:00<00:43,  3.64it/s]

Failed to fetch https://www.thecanadianencyclopedia.ca/en/article/george-brown: 403 Client Error: Forbidden for url: https://www.thecanadianencyclopedia.ca/en/article/george-brown
Failed to fetch https://www.thecanadianencyclopedia.ca/en/article/marcel-sabourin: 403 Client Error: Forbidden for url: https://www.thecanadianencyclopedia.ca/en/article/marcel-sabourin

 95%|█████████▌| 2794/2939 [41:07<01:07,  2.15it/s]

Failed to fetch https://www.theislandwiki.org/index.php/Government_House: 508 Server Error: Insufficient Resource for url: https://www.theislandwiki.org/index.php/Government_House

 96%|█████████▌| 2808/2939 [41:16<01:27,  1.49it/s]

Failed to fetch https://www.thestatesman.com/entertainment/why-virat-hardik-kl-rahul-have-unfollowed-26-year-old-punjabi-rapper-from-brampton-1503223635.html: 403 Client Error: Forbidden for url: https://www.thestatesman.com/entertainment/why-virat-hardik-kl-rahul-have-unfollowed-26-year-old-punjabi-rapper-from-brampton-1503223635.html
Failed to fetch https://www.thestatesman.com/sports/sachin-tendulkar-appointed-unicef-ambassador-for-the-icc-women-s-world-cup-1489144206.html: 403 Client Error: Forbidden for url: https://www.thestatesman.com/sports/sachin-tendulkar-appointed-unicef-ambassador-for-the-icc-women-s-world-cup-1489144206.html

 96%|█████████▌| 2810/2939 [41:27<07:04,  3.29s/it]

Failed to fetch https://www.thomascook.in/india-tourism/gulmarg-tourism/places-to-visit-in-gulmarg: HTTPSConnectionPool(host='www.thomascook.in', port=443): Read timed out. (read timeout=10)

 96%|█████████▌| 2812/2939 [41:38<07:55,  3.75s/it]

Failed to fetch https://www.thomascook.in/places-to-visit/ferozepur-nallah-in-gulmarg: HTTPSConnectionPool(host='www.thomascook.in', port=443): Read timed out. (read timeout=10)

 96%|█████████▌| 2815/2939 [41:41<03:55,  1.90s/it]

Failed to fetch https://www.tomb-of-ash.com/laras-musical-career/: 502 Server Error: Bad Gateway for url: https://www.tomb-of-ash.com/laras-musical-career/

 96%|█████████▌| 2817/2939 [41:44<03:02,  1.50s/it]

Failed to fetch https://www.topcount.co/tv/people/362294/china-zorrilla: 404 Client Error: Not Found for url: https://www.topcount.co/tv/people/362294/china-zorrilla

 97%|█████████▋| 2839/2939 [42:13<01:52,  1.13s/it]

Failed to fetch https://www.twooceansmarathon.org.za/about-two-oceans/history/: 404 Client Error: Not Found for url: https://www.twooceansmarathon.org.za/about-two-oceans/history/

 97%|█████████▋| 2842/2939 [42:25<05:26,  3.36s/it]

Failed to fetch https://www.uefa.com/uefachampionsleague/history/seasons/2019/groups/: HTTPSConnectionPool(host='www.uefa.com', port=443): Read timed out. (read timeout=10)

 97%|█████████▋| 2843/2939 [42:35<08:16,  5.17s/it]

Failed to fetch https://www.uefa.com/uefachampionsleague/match/2000488--bayern-vs-inter/: HTTPSConnectionPool(host='www.uefa.com', port=443): Read timed out. (read timeout=10)

 97%|█████████▋| 2844/2939 [42:45<10:20,  6.53s/it]

Failed to fetch https://www.uefa.com/uefachampionsleague/match/84101--barcelona-vs-arsenal/: HTTPSConnectionPool(host='www.uefa.com', port=443): Read timed out. (read timeout=10)

 97%|█████████▋| 2845/2939 [42:55<11:47,  7.53s/it]

Failed to fetch https://www.uefa.com/uefachampionsleague/news/0252-0e9902dd97ae-bd3c7b568287-1000--champions-league-2018-19-all-the-fixtures-and-results/: HTTPSConnectionPool(host='www.uefa.com', port=443): Read timed out. (read timeout=10)

 97%|█████████▋| 2846/2939 [42:58<09:26,  6.09s/it]

Failed to fetch https://www.ugcnepal.edu.np/frontpage/20: 404 Client Error: Not Found for url: https://www.ugcnepal.edu.np/frontpage/20

 97%|█████████▋| 2852/2939 [43:01<01:42,  1.18s/it]

Failed to fetch https://www.unicef.org/rosa/press-releases/sachin-tendulkar-appointed-unicef-and-cricket-good-ambassador-icc-womens-world-cup: 403 Client Error: Forbidden for url: https://www.unicef.org/rosa/press-releases/sachin-tendulkar-appointed-unicef-and-cricket-good-ambassador-icc-womens-world-cup
Failed to fetch https://www.unv.org/Annual-report/Annual-Report-2019: 403 Client Error: Forbidden for url: https://www.unv.org/Annual-report/Annual-Report-2019

 97%|█████████▋| 2854/2939 [43:02<01:16,  1.12it/s]

Failed to fetch https://www.usfigureskating.org/news/press-release/starr-andrews-added-2021-guaranteed-rate-skate-america: 404 Client Error: Not Found for url: https://usfigureskating.org/404-2.aspx?url=url%3d%2fnews%2fpress-release%2fstarr-andrews-added-2021-guaranteed-rate-skate-america
Failed to fetch https://www.usnwcarchives.org/repositories/2/resources/212: 403 Client Error: Forbidden for url: https://www.usnwcarchives.org/repositories/2/resources/212

 97%|█████████▋| 2860/2939 [43:04<00:31,  2.51it/s]

Failed to fetch https://www.vanguardngr.com/2020/05/the-death-of-justice-nabaruma-and-other-matters/: 403 Client Error: Forbidden for url: https://www.vanguardngr.com/2020/05/the-death-of-justice-nabaruma-and-other-matters/

 97%|█████████▋| 2862/2939 [43:04<00:23,  3.30it/s]

Failed to fetch https://www.veethi.com/india-people/p._n._bhagwati-profile-9617-18.htm: HTTPSConnectionPool(host='www.veethi.com', port=443): Max retries exceeded with url: /india-people/p._n._bhagwati-profile-9617-18.htm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f02896cdc10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

 97%|█████████▋| 2863/2939 [43:14<03:28,  2.74s/it]

Failed to fetch https://www.vercalendario.info/en/what/guinness-records-for-fastest_marathon_dressed_as_an_elf_male.html: HTTPSConnectionPool(host='www.vercalendario.info', port=443): Read timed out. (read timeout=10)

 98%|█████████▊| 2875/2939 [43:22<00:24,  2.61it/s]

Failed to fetch https://www.waymarking.com/waymarks/WMF776_Schiedam_The_Netherlands: 403 Client Error: Forbidden for url: https://www.waymarking.com/waymarks/WMF776_Schiedam_The_Netherlands
Failed to fetch https://www.wcpss.net/cms/lib/NC01911451/Centricity/Domain/264/100%20Cary%20Years.pdf: 404 Client Error: Not Found for url: https://www.wcpss.net/cms/lib/NC01911451/Centricity/Domain/264/100%20Cary%20Years.pdf

 98%|█████████▊| 2877/2939 [43:23<00:18,  3.29it/s]

Failed to fetch https://www.webelements.com/molybdenum/: 508 Server Error: Loop Detected for url: https://www.webelements.com/molybdenum/
Failed to fetch https://www.weforum.org/people/sergio-fajardo-valderrama/: 403 Client Error: Forbidden for url: https://www.weforum.org/people/sergio-fajardo-valderrama/

 99%|█████████▊| 2899/2939 [43:29<00:12,  3.22it/s]

Failed to fetch https://www.worldchangers.org/history: 404 Client Error: Not Found for url: https://worldchangers.org/history
Failed to fetch https://www.worldfootball.net/player_summary/hannes-fink/: 403 Client Error: Forbidden for url: https://www.worldfootball.net/player_summary/hannes-fink/

 99%|█████████▉| 2903/2939 [43:45<01:03,  1.75s/it]

Failed to fetch https://www.worldrecordacademy.com/medical/largest_human_DNA_helix_Bulgaria_breaks_Guinness_World_Records_record_216215.html: 406 Client Error: Not Acceptable for url: https://www.worldrecordacademy.com/medical/largest_human_DNA_helix_Bulgaria_breaks_Guinness_World_Records_record_216215.html
Failed to fetch https://www.worldtravelawards.com/award-worlds-leading-adventure-hotel-2022: 403 Client Error: Forbidden for url: https://www.worldtravelawards.com/award-worlds-leading-adventure-hotel-2022
Failed to fetch https://www.worldtravelawards.com/profile-31715-pikaia-lodge: 403 Client Error: Forbidden for url: https://www.worldtravelawards.com/profile-31715-pikaia-lodge
Failed to fetch https://www.worldwildlife.org/species/african-forest-elephant: 403 Client Error: Forbidden for url: https://www.worldwildlife.org/species/african-forest-elephant

 99%|█████████▉| 2908/2939 [43:47<00:25,  1.22it/s]

Failed to fetch https://www.xda-developers.com/cities-skylines-google-stadia/: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

 99%|█████████▉| 2910/2939 [43:48<00:18,  1.55it/s]

Failed to fetch https://www.yesasia.com/us/when-the-sun-goes-down-japan-version/1024605472-0-0-0-en/info.html: 403 Client Error: Forbidden for url: https://www.yesasia.com/us/when-the-sun-goes-down-japan-version/1024605472-0-0-0-en/info.html

100%|█████████▉| 2934/2939 [44:21<00:03,  1.67it/s]

Failed to fetch https://ysk.gov.tr/doc/dosyalar/Ingilizce/ElectionResults/2018CB-416D_en.pdf: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

100%|█████████▉| 2937/2939 [44:25<00:02,  1.08s/it]

Failed to fetch https://zenodo.org/records/6182816: 403 Client Error: Forbidden for url: https://zenodo.org/records/6182816

100%|██████████| 2939/2939 [44:26<00:00,  1.10it/s]

In [8]:
# printing the number of successfully fetched files
output_dir_lang = "language_texts"
fetched_files = len(os.listdir(output_dir_lang))
print(f"Fetched and stored {fetched_files} documents out of {len(unique_urls)}")

Fetched and stored 2419 documents out of 2939

In [9]:
set_langs = set(df['language'].dropna().unique())
print(set_langs)

{'Toba Batak', 'Urdu transliterate', 'Hindi transliterate', 'Urdu', 'Japanese', 'French', 'Marathi transliterate', 'Italian', 'Marathi', 'Bengali transliterate', 'Korean', 'Bengali', 'Spanish', 'Hindi', 'Indonesian', 'Simplified Chinese'}

In [11]:
language_codes = {
    "Toba Batak": "id",            # No dedicated ISO-639-1; Google uses Indonesian
    "Urdu": "ur",
    "Hindi": "hi",
    "Japanese": "ja",
    "French": "fr",
    "Marathi": "mr",
    "Italian": "it",
    "Bengali": "bn",
    "Korean": "ko",
    "Spanish": "es",
    "Indonesian": "id",
    "Simplified Chinese": "zh-cn"
}

In [7]:
from tqdm import tqdm
from googletrans import Translator
import time
import re
output_dir_translated = "language_texts_translated"
os.makedirs(output_dir_translated, exist_ok=True)

MAX_CHARS = 4500

def clean_text(text):
    """Remove common web noise from scraped text"""
    # Remove URLs
    text = re.sub(r'http\S+|www\.\S+', '', text)
    # Remove email addresses
    text = re.sub(r'\S+@\S+', '', text)
    # Remove excessive whitespace
    text = re.sub(r'\s+', ' ', text)
    # Remove common navigation/footer text patterns
    text = re.sub(r'(Home|Archive|Travel|Index|About Us|©.*)', '', text, flags=re.IGNORECASE)
    return text.strip()

lang_code = "en"
output_dir_lang = "language_texts"
output_dir_translated_lang = os.path.join(output_dir_translated, lang_code)   
for filename in tqdm(os.listdir(output_dir_lang)):
    file_path = os.path.join(output_dir_lang, filename)
    translated_file_path = os.path.join(output_dir_translated_lang, filename)
    
    if os.path.exists(translated_file_path):
        continue
        
    with open(file_path, "r", encoding="utf-8") as f:
        text = f.read()
    
    # Clean the text first
    text = clean_text(text)
    os.makedirs(output_dir_translated_lang, exist_ok=True)
    with open(translated_file_path, "w", encoding="utf-8") as f:
        f.write(text)

100%|██████████| 2419/2419 [03:20<00:00, 12.08it/s]

In [16]:
from tqdm import tqdm
from googletrans import Translator
import time
import re

translator = Translator()
output_dir_translated = "language_texts_translated"
os.makedirs(output_dir_translated, exist_ok=True)

MAX_CHARS = 4500

def clean_text(text):
    """Remove common web noise from scraped text"""
    # Remove URLs
    text = re.sub(r'http\S+|www\.\S+', '', text)
    # Remove email addresses
    text = re.sub(r'\S+@\S+', '', text)
    # Remove excessive whitespace
    text = re.sub(r'\s+', ' ', text)
    # Remove common navigation/footer text patterns
    text = re.sub(r'(Home|Archive|Travel|Index|About Us|©.*)', '', text, flags=re.IGNORECASE)
    return text.strip()

for key, lang_code in language_codes.items():
    print(f"Translating files to {key} ({lang_code})")
    output_dir_translated_lang = os.path.join(output_dir_translated, lang_code)
    os.makedirs(output_dir_translated_lang, exist_ok=True)
    
    for filename in tqdm(os.listdir(output_dir_lang)):
        file_path = os.path.join(output_dir_lang, filename)
        translated_file_path = os.path.join(output_dir_translated_lang, filename)
        
        if os.path.exists(translated_file_path):
            continue
            
        with open(file_path, "r", encoding="utf-8") as f:
            text = f.read()
        
        # Clean the text first
        text = clean_text(text)
        
        if not text or len(text) < 50:  # Skip very short texts
            continue
            
        try:
            if len(text) > MAX_CHARS:
                chunks = [text[i:i+MAX_CHARS] for i in range(0, len(text), MAX_CHARS)]
                translated_chunks = []
                for chunk in chunks:
                    result = translator.translate(chunk, dest=lang_code)
                    if result and result.text:
                        translated_chunks.append(result.text)
                    time.sleep(0.5)
                translated_text = " ".join(translated_chunks)
            else:
                result = translator.translate(text, dest=lang_code)
                translated_text = result.text if result else ""
            
            if translated_text:
                with open(translated_file_path, "w", encoding="utf-8") as f:
                    f.write(translated_text)
            
            time.sleep(0.3)
            
        except Exception as e:
            print(f"\nFailed to translate {filename} to {key}: {e}")
            time.sleep(2)

Translating files to Toba Batak (id)

  0%|          | 8/2419 [00:56<4:43:52,  7.06s/it]

KeyboardInterrupt:

In [ ]:
# from tqdm import tqdm
# # Now we need to translate these files into diff langauges using googletrans
# from googletrans import Translator
# translator = Translator()
# output_dir_translated = "language_texts_translated"
# os.makedirs(output_dir_translated, exist_ok=True)

# for key, lang_code in language_codes.items():
#     print(f"Translating files to {key} ({lang_code})")
#     output_dir_translated_lang = os.path.join(output_dir_translated, lang_code)
#     os.makedirs(output_dir_translated_lang, exist_ok=True)
    
#     for filename in tqdm(os.listdir(output_dir_lang)):
#         file_path = os.path.join(output_dir_lang, filename)
#         with open(file_path, "r", encoding="utf-8") as f:
#             text = f.read()
        
#         try:
#             # Translate text to the correct language
#             translated = translator.translate(text, dest=lang_code)
#             translated_text = translated.text

#             # Save translated text to the correct language folder
#             translated_file_path = os.path.join(output_dir_translated_lang, filename)
#             with open(translated_file_path, "w", encoding="utf-8") as f:
#                 f.write(translated_text)
#         except Exception as e:
#             print(f"Failed to translate {filename} to {key}: {e}")

Translating files to Toba Batak (id)

  0%|          | 0/2419 [00:00<?, ?it/s]

Failed to translate 1053.txt to Toba Batak: the JSON object must be str, bytes or bytearray, not NoneType

  0%|          | 1/2419 [00:07<5:20:22,  7.95s/it]

KeyboardInterrupt: